import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const oct2Articles = [
  {
    "slug": "phsa-paramedic-general-list-2026",
    "title": "PHSA Paramedic Diploma General Lists 2026 Released – Check Your Name",
    "category": "results",
    "organization": "Provincial Health Services Academy (PHSA), Health Dept, Govt of KP",
    "jobType": "2-Year Paramedic Diploma Merit / General Lists (Session 2026–2028)",
    "location": "Peshawar, D.I. Khan, Swat, Abbottabad (Khyber Pakhtunkhwa)",
    "qualification": "FSc Pre-Medical / Matric Science (As per PHSA Diploma Criteria)",
    "salary": "Government Paramedic Diploma Admissions (PIMT & PGPI Colleges)",
    "lastDate": "2026-10-15",
    "publishDate": "2026-10-02",
    "officialLink": "https://www.phsa.edu.pk/notice-details",
    "featured": true,
    "logoInitial": "PHSA",
    "featuredImage": "/images/phsa-paramedic-general-list-2026.svg",
    "imageAlt": "PHSA Paramedic Diploma General Lists 2026 Released Check Name",
    "excerpt": "PHSA Khyber Pakhtunkhwa has officially published the 2-Year Paramedic Diploma General Lists 2026 for PIMT D.I. Khan, Swat, Abbottabad, and PGPI Peshawar. Learn how to verify your name, submit objections, and access official PHSA PDF lists.",
    "seoTitle": "PHSA Paramedic General Lists 2026 Released – Check Your Name",
    "metaDescription": "Check PHSA Paramedic Diploma General Lists 2026 for PIMT D.I. Khan, Swat, Abbottabad, and PGPI Peshawar (phsa.edu.pk). View official list links, objection procedures, and merit details.",
    "isVerified": true,
    "schemaType": "Article",
    "content": [
      "### Executive Summary & Official Notice Release",
      "The **Provincial Health Services Academy (PHSA)**, operating under the Health Department, Government of Khyber Pakhtunkhwa, has officially published the **General Merit Lists** for admission into the **2-Year Paramedic Diploma Programs (Session 2026–2028)**. This release covers candidate submissions across major provincial paramedic training institutes including PIMT D.I. Khan, PIMT Swat, PIMT Abbottabad, and Post Graduate Paramedical Institute (PGPI) Peshawar.",
      "The notification was published on **October 1, 2026** (Notice #40) on the official PHSA website (`phsa.edu.pk/notice-details`). All candidates who submitted online applications for paramedic diploma programs are advised to verify their details, academic scores, and category merit standings immediately.",
      "### Quick Information Summary Table",
      "- **Executing Authority:** Provincial Health Services Academy (PHSA), Health Department KP",
      "- **Program Name:** 2-Year Paramedic Diploma Programs (Session 2026–2028)",
      "- **Notification Date:** October 1, 2026 (Official Notice #40)",
      "- **Participating Institutes:** PIMT D.I. Khan, PIMT Swat, PIMT Abbottabad, PGPI Peshawar",
      "- **List Type:** Provisional General Lists (Male, Female, Non-Catchment, Quota)",
      "- **Action Required:** Verify Personal Data, Marks Entry, & Submit Objections if required",
      "- **Official Verification Portal:** [phsa.edu.pk/notice-details](https://www.phsa.edu.pk/notice-details)",
      "### Institutions & List Categories Published",
      "PHSA has issued individual candidate lists categorized by training center, gender, and quota classification:",
      "1. **PIMT D.I. Khan Paramedic Lists:** General male and female merit lists, district quota lists, and non-catchment area applicants.",
      "2. **PIMT Swat Paramedic Lists:** Provisional candidate lists for Malakand division candidates across all clinical specialties.",
      "3. **PIMT Abbottabad Paramedic Lists:** Hazara division paramedic applicant rosters for diploma seats.",
      "4. **PGPI Peshawar Paramedic Lists:** Central provincial merit lists for specialized paramedic training modules at Peshawar.",
      "### Paramedic Diploma Disciplines Covered",
      "The published General Lists include applicants across various 2-year allied health diploma tracks, including:",
      "- Diploma in Cardiology Technology",
      "- Diploma in Surgical / Operation Theater Technology",
      "- Diploma in Pathology / Medical Lab Technology (MLT)",
      "- Diploma in Radiology / X-Ray Technology",
      "- Diploma in Dental Health Technology",
      "- Diploma in Anesthesia Technology",
      "- Diploma in Pharmacy Technician / Dispenser Track",
      "- Diploma in Health / Dialysis / ICU Technology",
      "### How to Check Your Name & Verify Details",
      "To check your status on the official PHSA Paramedic General Lists 2026, follow these official steps:",
      "1. **Visit Official Site:** Open the PHSA Notice Board at `https://www.phsa.edu.pk/notice-details`.",
      "2. **Locate Notice #40:** Click on **Notice #40: General Lists – Paramedic Diploma Programs (2 Years)** dated 01-Oct-2026.",
      "3. **Select Your Institute:** Choose your respective institute PDF link (PIMT D.I. Khan, Swat, Abbottabad, or PGPI Peshawar).",
      "4. **Search Your Record:** Open the PDF document and use the `Ctrl + F` search function to enter your **Application Form Number**, **CNIC / B-Form Number**, or **Full Name**.",
      "5. **Review Score Calculation:** Verify your Matric science marks, FSc marks (where applicable), age, district of domicile, and quota allocation.",
      "### Objection Submission & Record Correction Guidelines",
      "If you identify any discrepancy in your name, academic marks, domicile status, or assigned quota, you must follow the official PHSA grievance procedure:",
      "- **Objection Filing Window:** Candidates must present original credentials to the designated admission committee at the respective institute within the announced window.",
      "- **Required Proof:** Bring original Matric DMC, FSc DMC, Domicile certificate, CNIC/B-Form, and paid application fee voucher.",
      "- **Final Merit List:** After resolving valid objections and verifying original documents, PHSA will issue the Final Selection / Call List for interview and fee submission.",
      "### Candidate Privacy & Security Compliance Notice",
      "In compliance with official data protection standards, **CareerDost does NOT host, mirror, or republish personal candidate records, CNIC numbers, or private mark sheets**. Readers are directed exclusively to official PHSA PDF portals to view public merit listings.",
      "### Official Links & Verification Resources",
      "- **PHSA Paramedic General Lists Notice:** [PHSA Notice Board](https://www.phsa.edu.pk/notice-details)",
      "- **PHSA Official Portal:** [PHSA Khyber Pakhtunkhwa](https://www.phsa.edu.pk/)",
      "- **Related KP Health Program:** Explore [KP Government BS Nursing Admissions 2026–2030](/jobs/phsa-kp-bs-nursing-admissions-2026) for 4-year degree opportunities.",
      "### Frequently Asked Questions (FAQ)",
      "**Q1: Where can I download the PHSA Paramedic General List 2026 PDF?**\nYou can download the official PDF documents directly from the PHSA Notice Details page at `phsa.edu.pk/notice-details` under Notice #40.",
      "**Q2: What is the difference between a General List and a Final Selection List?**\nThe General List is a provisional record of all received applications showing candidate details for correction. The Final Selection List is issued after objections are resolved to announce admitted candidates.",
      "**Q3: What should I do if my marks are calculated incorrectly?**\nVisit the respective PIMT institute or PHSA admissions office with your original DMCs and application copy before the objection deadline to rectify your record.",
      "**Q4: Are hostel facilities provided for paramedic diploma students?**\nHostel accommodation is subject to seat availability at respective institutes (PGPI Peshawar, PIMT D.I. Khan, Swat, Abbottabad) according to provincial health department rules."
    ]
  },
  {
    "slug": "hec-outstanding-research-awards-2026-27",
    "title": "HEC Research Awards 2026–27 – Win Up to Rs1 Million",
    "category": "career-guides",
    "organization": "Higher Education Commission (HEC) Pakistan",
    "jobType": "National Research Awards & Cash Grants",
    "location": "Islamabad & All HEC Recognized Universities across Pakistan",
    "qualification": "PhD / University Faculty / Researchers / Postdoctoral Fellows",
    "salary": "Cash Prize Up to Rs 1,000,000 (Rs 1 Million) + Citation Certificate",
    "lastDate": "2026-10-31",
    "publishDate": "2026-10-02",
    "officialLink": "https://www.hec.gov.pk/english/services/faculty/HEC%20Outstanding%20Research%20Awards/Pages/Introduction.aspx",
    "featured": true,
    "logoInitial": "HEC",
    "featuredImage": "/images/hec-outstanding-research-awards-2026-27.svg",
    "imageAlt": "HEC Outstanding Research Awards 2026-27 Apply Online",
    "excerpt": "HEC Pakistan invites online applications for the Outstanding Research Awards 2026–27. Academic researchers can win cash prizes up to Rs 1,000,000 across Best Publication, Best Researcher, and Best Young Researcher categories before October 31, 2026.",
    "seoTitle": "HEC Research Awards 2026–27 – Win Up to Rs1 Million",
    "metaDescription": "Apply online for HEC Outstanding Research Awards 2026–27 (research.hec.gov.pk). View eligibility for Best Publication (Rs 1M), Best Researcher (Rs 500k), and Best Young Researcher (Rs 500k). Deadline Oct 31, 2026.",
    "isVerified": true,
    "schemaType": "Article",
    "content": [
      "### Executive Summary & Official Award Announcement",
      "The **Higher Education Commission (HEC) Pakistan** has officially announced the call for applications for the **HEC Outstanding Research Awards 2026–27**. Designed to recognize and reward exceptional scholarly research, innovative publications, and academic contributions, the awards offer cash prizes of **up to Rs 1,000,000 (Rs 1 Million)** alongside prestigious national citation plaques.",
      "Full-time university faculty, independent researchers, and postdoctoral scholars working in HEC-recognized higher education institutions across Pakistan and AJ&K are invited to submit their research achievements via the official HEC portal (`research.hec.gov.pk`) on or before **October 31, 2026**.",
      "### Award Categories & Prize Money Breakdown",
      "HEC confers awards across three primary competitive categories. Applicants must note that prize money varies by award type:",
      "1. **Best Publication Award:** Cash prize of **Rs 1,000,000 (Rs 1 Million)** + Certificate of Citation. Awarded for landmark original research papers published in top-tier peer-reviewed international journals.",
      "2. **Best Researcher Award:** Cash prize of **Rs 500,000** + Certificate of Citation. Conferred upon active researchers demonstrating sustained high-impact research output, citations, and institutional leadership.",
      "3. **Best Young Researcher Award:** Cash prize of **Rs 500,000** + Certificate of Citation. Reserved for promising early-career scholars **under 40 years of age** as of January 1, 2026.",
      "### Eligible Academic Disciplines",
      "Applications are open across six major academic disciplines recognized by HEC:",
      "- Biological Sciences & Agricultural Sciences",
      "- Physical Sciences, Mathematics, & Earth Sciences",
      "- Engineering, Technology, & Computer Science",
      "- Social Sciences & Economics",
      "- Humanities & Art History",
      "- Management Sciences & Business Administration",
      "### Comprehensive Eligibility Criteria",
      "To be eligible for nomination or direct application for HEC Research Awards 2026–27, candidates must satisfy the following institutional standards:",
      "- **Institutional Affiliation:** Applicants must be regular, contract, or tenure-track faculty members or active research staff at an HEC-recognized public or private university/degree-awarding institution in Pakistan.",
      "- **Publication Window:** Research papers submitted for the Best Publication category must have been published in a recognized Web of Science / Scopus indexed journal within the designated official publication window.",
      "- **Age Limit for Young Researcher:** Candidates applying under the Best Young Researcher category must be under 40 years of age on **January 1, 2026**.",
      "- **Originality & Ethics:** Submissions must conform to HEC Plagiarism Policy and ethical research practices. Duplicate applications previously awarded an HEC national prize are ineligible.",
      "### Step-by-Step Online Application Process",
      "1. **Access HEC Portal:** Visit the HEC Research Portal at `https://research.hec.gov.pk`.",
      "2. **Account Registration:** Login with your existing HEC CNIC credentials or create a new profile.",
      "3. **Select Award Category:** Navigate to *Services -> Faculty Services -> HEC Outstanding Research Awards 2026–27*.",
      "4. **Complete Profile & Upload Documents:** Fill out applicant details, publication list, citation index proof, and upload PDF copies of published articles.",
      "5. **Institutional Endorsement:** Print the generated application summary, obtain endorsement from the Vice Chancellor / Rector / Head of Institution, and upload the signed endorsement page.",
      "6. **Final Submission:** Submit the electronic application before **October 31, 2026**.",
      "### Required Documentation Checklist",
      "- Copy of CNIC / Passport",
      "- Institutional Appointment Letter / Official Card",
      "- Complete Curriculum Vitae (CV) with Google Scholar & Scopus Profile links",
      "- Full-text PDF copy of submitted research paper(s)",
      "- Proof of Journal Impact Factor / Journal Citation Reports (JCR) ranking",
      "- Signed Institutional Endorsement Letter",
      "### Evaluation & Selection Mechanism",
      "Submissions undergo a multi-tier evaluation process managed by national and international discipline experts:",
      "- **Technical Scrutiny:** HEC verifies publication credentials, indexing, and compliance.",
      "- **Peer Review:** Expert panels evaluate scientific novelty, methodology, citation impact, and practical societal applications.",
      "- **Final Approval:** HEC National Research Committee confirms final winners.",
      "### Official Links & Further Opportunities",
      "- **HEC Award Details Page:** [HEC Outstanding Research Awards](https://www.hec.gov.pk/english/services/faculty/HEC%20Outstanding%20Research%20Awards/Pages/Introduction.aspx)",
      "- **Online Application Portal:** [HEC Research Portal](https://research.hec.gov.pk)",
      "- **Higher Education Guidance:** Interested in international research mobility? Read our guide on [Commonwealth Scholarships 2027–28 for Pakistani Students](/jobs/commonwealth-scholarships-2027-28-pakistan-hec-csc-uk).",
      "### Frequently Asked Questions (FAQ)",
      "**Q1: What is the last date to apply for HEC Research Awards 2026–27?**\nThe closing date for online application submission on the HEC portal is **October 31, 2026**.",
      "**Q2: Does every award recipient get Rs 1 million?**\nNo. The Best Publication Award carries a cash prize of **Rs 1,000,000**, while the Best Researcher and Best Young Researcher awards carry **Rs 500,000** each.",
      "**Q3: Can co-authors apply for the Best Publication award?**\nYes, but the principal/corresponding author with primary institutional affiliation in Pakistan must submit the application along with consent from co-authors as per HEC guidelines.",
      "**Q4: Is hardcopy document submission required?**\nApplications are submitted online via `research.hec.gov.pk`. Hard copies are only required if specifically requested by HEC after initial shortlisting."
    ]
  },
  {
    "slug": "cbd-punjab-paid-internship-2026-youth-career-program",
    "title": "CBD Punjab Paid Internship 2026 – Youth Career Program for Fresh Graduates",
    "category": "internships",
    "organization": "Punjab Central Business District Development Authority (PCBDDA / CBD Punjab)",
    "jobType": "Paid Graduate Internship (Youth Career Program 2026)",
    "location": "Lahore, Punjab",
    "qualification": "Minimum 16 Years Education (BS/BE/BBA/MA/MSc/LLB) • CGPA ≥ 3.0 • Age ≤ 25",
    "salary": "Market Competitive Paid Monthly Stipend + Professional Certificate",
    "lastDate": "2026-10-12",
    "publishDate": "2026-10-02",
    "officialLink": "https://www.cbdpunjab.gov.pk/ycp2026",
    "featured": true,
    "logoInitial": "CBD",
    "featuredImage": "/images/cbd-punjab-paid-internship-2026.svg",
    "imageAlt": "CBD Punjab Paid Internship 2026 Youth Career Program Apply Online",
    "excerpt": "CBD Punjab (PCBDDA) announces the Youth Career Program (YCP 2026) paid internship for fresh graduates with 16 years of education, CGPA 3.0+, and maximum age 25. Apply online by October 12, 2026.",
    "seoTitle": "CBD Punjab Paid Internship 2026 – Youth Career Program for Fresh Graduates",
    "metaDescription": "Apply online for CBD Punjab Paid Internship 2026 Youth Career Program (cbdpunjab.gov.pk/ycp2026). Check criteria for 16-year graduates, 3.0 CGPA, age 25, and deadline Oct 12, 2026.",
    "isVerified": true,
    "schemaType": "JobPosting",
    "content": [
      "### Executive Summary & Program Announcement",
      "The **Punjab Central Business District Development Authority (PCBDDA)**, prominently known as **CBD Punjab**, has officially launched the **Youth Career Program (YCP 2026)**. This paid internship initiative is designed to provide fresh, high-achieving university graduates with hands-on professional experience, mentorship, and practical training in high-impact urban development projects.",
      "The program offers structured corporate exposure across engineering, technology, finance, legal, and urban planning disciplines. Eligible fresh graduates across Punjab can submit online applications at `cbdpunjab.gov.pk/ycp2026` before the official deadline of **October 12, 2026**.",
      "### Quick Information Overview Table",
      "- **Organization:** Punjab Central Business District Development Authority (PCBDDA / CBD Punjab)",
      "- **Program Name:** Youth Career Program (YCP 2026) Paid Internship",
      "- **Internship Duration:** Up to 3 Months (Hands-on Corporate Training)",
      "- **Remuneration:** Market Competitive Paid Monthly Stipend + Official Certificate",
      "- **Education Requirement:** Minimum 16 Years Higher Education (BS / BE / BBA / MA / MSc / LLB)",
      "- **Minimum Academic Standing:** CGPA $\\ge$ 3.0 out of 4.0 (or equivalent first division)",
      "- **Age Limit:** Maximum 25 Years as of Application Closing Date",
      "- **Job Location:** CBD Punjab Headquarters, Lahore",
      "- **Application Deadline:** **October 12, 2026**",
      "- **Official Application Portal:** [cbdpunjab.gov.pk/ycp2026](https://www.cbdpunjab.gov.pk/ycp2026)",
      "### Available Internship Disciplines",
      "CBD Punjab is offering internship placements across diverse specialized departments:",
      "1. **Engineering & Technical Services:** Civil Engineering, Structural Engineering, Architecture, Urban & Regional Planning, Electrical / Mechanical Engineering.",
      "2. **Information Technology & GIS:** Software Engineering, IT Infrastructure, Data Analytics, Geographic Information Systems (GIS).",
      "3. **Finance, Commercial & Real Estate:** Financial Analysis, Accounting, Corporate Finance, Commercial Strategy, Real Estate Asset Management.",
      "4. **Human Resources & Corporate Governance:** HR Management, Public Relations, Operations, Legal Affairs (LLB graduates).",
      "5. **Marketing & Media Communication:** Digital Marketing, Content Strategy, Graphic Design, Brand Communications.",
      "### Mandatory Eligibility Criteria",
      "Applicants must meet all specified conditions to qualify for shortlisting:",
      "- **Qualification:** Must possess a 4-year Bachelor's degree (BS / BE / BBA / LLB) or Master's degree (16 years of education) from an HEC-recognized university.",
      "- **Academic Performance:** Minimum Cumulative Grade Point Average (CGPA) of **3.0 out of 4.0**.",
      "- **Fresh Graduate Status:** Open to recently graduated candidates seeking practical industry induction.",
      "- **Age Limit:** Upper age limit of **25 years** on the closing date of applications (**October 12, 2026**).",
      "- **Domicile:** Open to candidates holding valid Punjab Domicile.",
      "### Program Benefits & Learning Outcomes",
      "- **Market Competitive Stipend:** Paid monthly financial stipend during the internship tenure.",
      "- **Real-World Project Exposure:** Work directly on mega infrastructure, commercial development, and smart city initiatives in Lahore.",
      "- **Professional Mentorship:** Executive guidance from top industry leaders, engineers, and financial strategists.",
      "- **Career Certification:** Official PCBDDA Certificate of Completion enhancing future employment prospects.",
      "### Step-by-Step \"How to Apply Online\" Guide",
      "1. **Access Portal:** Open the official CBD Punjab YCP portal at `https://www.cbdpunjab.gov.pk/ycp2026`.",
      "2. **Form Registration:** Enter basic personal details, CNIC number, email address, and phone number.",
      "3. **Academic Data Entry:** Fill in degree title, university name, completion year, and exact CGPA.",
      "4. **Department Selection:** Choose your preferred department / discipline aligned with your degree.",
      "5. **Upload Resume & Credentials:** Attach your updated CV, transcript copy, and CNIC scan.",
      "6. **Review & Submit:** Double-check all information and submit the application prior to **October 12, 2026**.",
      "### Required Documentation Checklist",
      "- Updated Curriculum Vitae (CV)",
      "- Copy of CNIC",
      "- Official University Transcript / Final Degree Certificate showing CGPA $\\ge$ 3.0",
      "- Domicile Certificate of Punjab",
      "### Official Application Portal & Sources",
      "- **Official YCP Portal:** [CBD Punjab YCP 2026 Portal](https://www.cbdpunjab.gov.pk/ycp2026)",
      "- **Main Authority Website:** [CBD Punjab Official Site](https://www.cbdpunjab.gov.pk/)",
      "- **Explore Higher Research Opportunities:** Learn about the [HEC Research Awards 2026–27](/jobs/hec-outstanding-research-awards-2026-27).",
      "### Frequently Asked Questions (FAQ)",
      "**Q1: What is the application deadline for CBD Punjab Internship 2026?**\nThe last date to apply online is **October 12, 2026**.",
      "**Q2: What is the stipend amount for YCP 2026?**\nCBD Punjab provides a market-competitive paid stipend to selected interns as determined by authority guidelines.",
      "**Q3: Can students with CGPA below 3.0 apply?**\nNo. The official eligibility criteria strictly mandates a minimum CGPA of 3.0 out of 4.0.",
      "**Q4: Is the internship open to graduates from all over Pakistan?**\nThe program primary targets candidates holding Punjab domicile for placements at CBD Punjab headquarters in Lahore."
    ]
  },
  {
    "slug": "phsa-kp-bs-nursing-admissions-2026",
    "title": "KP Government BS Nursing Admissions 2026–2030 – Apply Online",
    "category": "admissions",
    "organization": "Provincial Health Services Academy (PHSA), Health Dept, Govt of KP",
    "jobType": "Government Nursing Admissions (4-Year Degree)",
    "location": "Khyber Pakhtunkhwa (Peshawar & All Govt Nursing Colleges)",
    "qualification": "FSc Pre-Medical (50% Min Marks) + KMU-CAT + KP/Merged Districts Domicile",
    "salary": "BS Nursing Session 2026–2030 (Govt Stipend as per Rules)",
    "lastDate": "2026-10-16",
    "publishDate": "2026-10-02",
    "officialLink": "https://www.phsa.edu.pk/admissions",
    "featured": true,
    "logoInitial": "PHSA",
    "featuredImage": "/images/phsa-kp-bs-nursing-admissions-2026.svg",
    "imageAlt": "KP Government BS Nursing Admissions 2026 PHSA Apply Online",
    "excerpt": "PHSA Khyber Pakhtunkhwa has officially announced online admissions for 4-year BS Nursing (Session 2026-2030) across government nursing colleges. Check FSc Pre-Medical eligibility, KMU-CAT score, domicile rules, and application deadline of October 16, 2026.",
    "seoTitle": "KP Government BS Nursing Admissions 2026–2030 – Apply Online",
    "metaDescription": "Apply online for KP Government BS Nursing Admissions 2026-2030 via PHSA portal (phsa.edu.pk). View eligibility for FSc Pre-Medical, KMU-CAT requirement, nursing colleges, and deadline Oct 16, 2026.",
    "isVerified": true,
    "schemaType": "Article",
    "content": [
      "### Executive Summary & Official Admission Notice",
      "The **Provincial Health Services Academy (PHSA)**, operating under the Health Department, Government of Khyber Pakhtunkhwa, has officially announced the commencement of online admissions for the **4-Year BS Nursing Degree Program (Session 2026–2030)** across participating government nursing colleges in Khyber Pakhtunkhwa.",
      "Online registration opened on **September 29, 2026**, and candidates seeking admission to government nursing institutions must submit their online applications via the official PHSA Applicant Portal before the closing date of **October 16, 2026**.",
      "### Quick Information Overview Table",
      "- **Degree Program:** Bachelor of Science in Nursing (BS Nursing – 4 Years)",
      "- **Academic Session:** 2026–2030",
      "- **Executing Body:** Provincial Health Services Academy (PHSA), Health Dept, Govt of KP",
      "- **Target Institutions:** Affiliated Government College of Nursing (GCN) Campuses in KP",
      "- **Basic Eligibility:** FSc Pre-Medical (Minimum 50% Marks) & Mandatory KMU-CAT Result",
      "- **Domicile Requirement:** Khyber Pakhtunkhwa (KP) & Merged Districts (FATA)",
      "- **Online Application Opening Date:** September 29, 2026",
      "- **Online Application Deadline:** **October 16, 2026**",
      "- **Official Admission Portal:** [phsa.edu.pk/admissions](https://www.phsa.edu.pk/admissions)",
      "### Academic Eligibility Criteria & Entry Test Requirements",
      "Candidates applying for government nursing admissions in KP must satisfy the following criteria:",
      "- **Educational Qualification:** Higher Secondary School Certificate (HSSC / FSc Pre-Medical) with Physics, Chemistry, and Biology, securing a minimum of **50% unadjusted marks** from a recognized Board of Intermediate and Secondary Education (BISE).",
      "- **KMU-CAT Mandatory Test:** Candidates must have appeared in the **Khyber Medical University Centralized Admission Test (KMU-CAT)**. Entry test marks are integrated into the final merit calculation.",
      "- **Domicile Criteria:** Applicants must possess a valid **Domicile Certificate of Khyber Pakhtunkhwa** or Merged Tribal Districts (FATA).",
      "- **Age Limit:** 18 to 25 years as of the closing date of application (or as specified in the official PHSA prospectus).",
      "### Participating Government Nursing Colleges",
      "Submissions allow applicants to rank participating public sector nursing colleges in KP during online form submission, including:",
      "- College of Nursing, Post Graduate College of Nursing (PGCN), Peshawar",
      "- Government College of Nursing (GCN), Hayatabad, Peshawar",
      "- Government College of Nursing, Mardan",
      "- Government College of Nursing, Swat",
      "- Government College of Nursing, Abbottabad",
      "- Government College of Nursing, Kohat",
      "- Government College of Nursing, Bannu",
      "- Government College of Nursing, D.I. Khan",
      "- Government College of Nursing, Jamrud (Khyber District)",
      "### Step-by-Step \"How to Apply Online\" Guide",
      "1. **Step 1:** Access the official PHSA Applicant Portal at `https://www.phsa.edu.pk/admissions`.",
      "2. **Step 2:** Create an applicant account using your CNIC/B-Form number, active mobile number, and personal email address.",
      "3. **Step 3:** Generate and print the auto-generated bank application processing fee challan, deposit the fee at the designated bank, and upload a clear photo/scan of the paid receipt.",
      "4. **Step 4:** Enter your Matric, FSc Pre-Medical, and KMU-CAT test marks exactly as printed on your official DMCs.",
      "5. **Step 5:** Upload clear scanned copies of required documents (CNIC/B-Form, Domicile, FSc DMC, Matric Certificate, Photograph).",
      "6. **Step 6:** Rank your preferred participating nursing colleges in order of preference.",
      "7. **Step 7:** Review your profile carefully and submit before **October 16, 2026**.",
      "### Required Documents Checklist",
      "- Recent Passport-Size Photograph",
      "- CNIC or B-Form copy",
      "- KP / Merged Districts Domicile Certificate",
      "- Matriculation (SSC) Detailed Marks Certificate (DMC)",
      "- FSc Pre-Medical (HSSC) Detailed Marks Certificate (DMC)",
      "- KMU-CAT Official Test Result Card",
      "- Paid Application Fee Bank Voucher / Receipt",
      "- Quota Certificate (if applying under Minority, Disability, or PHSA Network reserved seats)",
      "### Selection & Merit List Procedure",
      "- **Document Verification:** PHSA scrutinizes all online applications and mark entries.",
      "- **Correction Window:** If any discrepancy is identified, the application is returned to the applicant portal with remarks for online correction before final lock.",
      "- **Merit List Display:** Provisional and final merit lists will be published on the PHSA website.",
      "- For 2-year paramedic lists, view [PHSA Paramedic Diploma General Lists 2026](/jobs/phsa-paramedic-general-list-2026).",
      "### Official Source & Apply Links",
      "- **Official Admission Portal:** [PHSA KP Admissions Portal](https://www.phsa.edu.pk/admissions)",
      "- **PHSA Main Website:** [PHSA KP Official Website](https://www.phsa.edu.pk/)",
      "### Frequently Asked Questions (FAQ)",
      "**Q1: What is the last date to apply for PHSA KP BS Nursing Admissions 2026?**\nThe last date to submit online applications on the PHSA portal is **October 16, 2026**.",
      "**Q2: Is KMU-CAT mandatory for KP BS Nursing admission?**\nYes, KMU-CAT entry test marks are mandatory for merit calculation in KP public sector nursing colleges.",
      "**Q3: What is the minimum FSc percentage required?**\nApplicants must have passed FSc Pre-Medical with at least 50% unadjusted marks.",
      "**Q4: Can candidates from other provinces apply on open merit?**\nNo, admissions in KP government nursing colleges are open to candidates holding KP or Merged Districts (FATA) domicile."
    ]
  },
  {
    "slug": "commonwealth-scholarships-2027-28-pakistan-hec-csc-uk",
    "title": "Commonwealth Scholarships 2027–28 for Pakistani Students – Master’s & PhD",
    "category": "scholarships",
    "organization": "HEC Pakistan & Commonwealth Scholarship Commission (CSC) UK",
    "jobType": "Fully Funded UK Master's & PhD Scholarships",
    "location": "United Kingdom (UK Universities)",
    "qualification": "16 Years Education (Master's) / 17-18 Years (PhD) • HEC HAT Score ≥ 60",
    "salary": "100% Tuition Fee + Monthly Stipend (£1,347–£1,652/mo) + Airfare",
    "lastDate": "2026-10-20",
    "publishDate": "2026-10-02",
    "officialLink": "https://www.hec.gov.pk/english/HECAnnouncements/Pages/CW-Scholarship.aspx",
    "featured": true,
    "logoInitial": "HEC",
    "featuredImage": "/images/commonwealth-scholarship-2027-28.svg",
    "imageAlt": "Commonwealth Scholarships 2027-28 Pakistan HEC CSC UK Apply Online",
    "excerpt": "HEC Pakistan announces Commonwealth Scholarships 2027–28 for Pakistani and AJ&K citizens to pursue fully funded Master's and PhD degrees in the UK. Dual application on HEC and CSC portals required by October 20, 2026.",
    "seoTitle": "Commonwealth Scholarships 2027–28 for Pakistani Students – Master’s & PhD",
    "metaDescription": "Apply for Commonwealth Scholarships 2027–28 via HEC & CSC portals. Fully funded Master's and PhD in UK for Pakistani/AJ&K students. Check HAT score criteria and deadline Oct 20, 2026.",
    "isVerified": true,
    "schemaType": "Article",
    "content": [
      "### Executive Summary & Official Announcement",
      "The **Higher Education Commission (HEC) Pakistan**, in partnership with the **Commonwealth Scholarship Commission (CSC) UK**, has officially opened applications for the **Commonwealth Scholarships 2027–28**. This prestigious program enables high-achieving Pakistani and AJ&K citizens to pursue fully funded **Master's** (1-year taught) and **PhD** (3-year research) degree programs at top-ranked universities across the United Kingdom.",
      "Applicants must complete a mandatory **dual application process** on both the HEC Online Portal and the CSC Electronic Application System (EAS) before the official deadline of **October 20, 2026**.",
      "### Quick Information Overview Table",
      "- **Awarding Bodies:** Commonwealth Scholarship Commission (CSC) UK & HEC Pakistan",
      "- **Target Audience:** Pakistani National & AJ&K Permanent Residents",
      "- **Degree Levels:** 1-Year Master's Degree & 3-Year PhD Degree",
      "- **Financial Coverage:** 100% Fully Funded (Tuition, Monthly Stipend, Airfare, Allowance)",
      "- **HEC HAT Requirement:** Minimum **60 out of 100** score in HEC Higher Education Aptitude Test (HAT)",
      "- **HEC Nomination Quota:** **26 Master's Nominations** & **30 General PhD Nominations**",
      "- **Dual Application Mandate:** Submissions required on BOTH HEC & CSC portals",
      "- **Application Deadline:** **October 20, 2026**",
      "- **Official HEC Notice Page:** [hec.gov.pk Announcements](https://www.hec.gov.pk/english/HECAnnouncements/Pages/CW-Scholarship.aspx)",
      "### Scholarship Financial Benefits",
      "Commonwealth Scholarships cover full financial costs for successful awardees:",
      "- **Full Tuition Fees:** Direct payment of 100% university tuition fees.",
      "- **Monthly Living Stipend:** £1,347 per month (or £1,652 per month for universities in the London metropolitan area).",
      "- **International Airfare:** Return economy class flights from Pakistan to the UK.",
      "- **Warm Clothing & Study Allowance:** Additional grants for arrival expenses, thesis preparation, and study travel.",
      "### Mandatory Eligibility Criteria",
      "1. **Nationality:** Must be a citizen or permanent resident of Pakistan or Azad Jammu & Kashmir (AJ&K).",
      "2. **Academic Background:**",
      "   - For Master's: 16 years of education (BS 4-Year / MA / MSc / BE / BBA) from an HEC-recognized university.",
      "   - For PhD: 17/18 years of education (MS / MPhil / ME) with strong research proposal alignment.",
      "3. **HEC HAT Score:** Must have achieved a minimum valid score of **60/100** in HEC HAT test.",
      "4. **Financial Need:** Must certify inability to afford studying in the UK without scholarship support.",
      "### The Six Commonwealth Development Themes",
      "Applicants must align their study plan and future career goals with one of the six strategic development themes:",
      "1. Science and technology for development",
      "2. Strengthening health systems and capacity",
      "3. Promoting global prosperity",
      "4. Strengthening global peace, security and governance",
      "5. Strengthening resilience and response to crises",
      "6. Access, inclusion and opportunity",
      "### Step-by-Step Dual Application Guide",
      "Candidates must complete BOTH applications sequentially:",
      "#### Part A: CSC UK Application System (EAS)",
      "1. Visit the CSC Online Application System (EAS) for Master's or PhD.",
      "2. Register, fill out personal statement, study plan, development impact essay, and upload academic documents.",
      "3. Submit the CSC application before **October 20, 2026**.",
      "#### Part B: HEC Online Portal",
      "1. Visit `https://scholarship.hec.gov.pk`.",
      "2. Select *Learning Opportunities Abroad (LOA) -> Commonwealth Scholarships 2027–28*.",
      "3. Enter HEC HAT test details, upload CSC application confirmation, and submit fee payment.",
      "4. Complete submission prior to **October 20, 2026**.",
      "### CRITICAL RULE: Nomination vs Final Selection",
      "**Important Clarification:** Being nominated by HEC Pakistan does **NOT** guarantee final selection for the Commonwealth Scholarship. HEC submits 26 Master's and 30 PhD nominations to the UK Commonwealth Scholarship Commission. The final selection decision rests exclusively with the CSC UK selection panel based on global merit evaluation.",
      "### Official Links & Verification Portals",
      "- **Official HEC Announcement:** [HEC Commonwealth Page](https://www.hec.gov.pk/english/HECAnnouncements/Pages/CW-Scholarship.aspx)",
      "- **HEC Scholarship Portal:** [HEC Online Admissions Portal](https://scholarship.hec.gov.pk)",
      "- **UK CSC Official Guide:** [BridgeUSA & International Opportunities](https://j1visa.state.gov/programs/teacher/)",
      "- **Local Research Awards:** Explore the [HEC Research Awards 2026–27](/jobs/hec-outstanding-research-awards-2026-27).",
      "### Frequently Asked Questions (FAQ)",
      "**Q1: What is the last date to submit Commonwealth Scholarship applications for 2027–28?**\nThe closing deadline for both HEC and CSC portal submissions is **October 20, 2026**.",
      "**Q2: Is HEC HAT test mandatory?**\nYes. Candidates must have a minimum HAT score of 60 out of 100 to qualify for HEC nomination.",
      "**Q3: Does HEC nomination guarantee a scholarship?**\nNo. HEC nominates shortlisted candidates, but final selection is determined solely by the Commonwealth Scholarship Commission in the UK.",
      "**Q4: Can I apply without an IELTS score?**\nWhile CSC does not require IELTS at initial application, target UK universities may require English proficiency proof upon conditional admission."
    ]
  }
];

const listingsFilePath = path.join(__dirname, '../src/data/listings.js');

import(`file://${listingsFilePath}`).then(({ listings }) => {
  const existingSlugsToRemove = new Set(oct2Articles.map(a => a.slug));
  const filteredListings = listings.filter(l => !existingSlugsToRemove.has(l.slug));

  const updatedListings = [...oct2Articles, ...filteredListings];

  const helperFunctions = `

export const getListingBySlug = (slug) => listings.find((l) => l.slug === slug)

export const getListingsByCategory = (categorySlug) =>
  listings
    .filter((l) => l.category === categorySlug)
    .sort((a, b) => new Date(b.publishDate) - new Date(a.publishDate))

export const getFeaturedListings = () =>
  listings.filter((l) => l.featured).sort((a, b) => new Date(b.publishDate) - new Date(a.publishDate))

export const getLatestListings = (limit = 12) =>
  [...listings]
    .sort((a, b) => new Date(b.publishDate) - new Date(a.publishDate))
    .slice(0, limit)

export const searchListings = (query) => {
  const q = query.trim().toLowerCase()
  if (!q) return []
  return listings.filter((l) =>
    [l.title, l.organization, l.location, l.category]
      .join(' ')
      .toLowerCase()
      .includes(q)
  )
}
`;

  const newFileContent = `// Sample content only — no backend yet. Shape mirrors the fields the admin
// panel will eventually write: title, slug, category, organization, jobType,
// location, qualification, salary, lastDate, officialLink, content, seo.
export const listings = ${JSON.stringify(updatedListings, null, 2)};
${helperFunctions}`;

  fs.writeFileSync(listingsFilePath, newFileContent, 'utf8');
  console.log(`Successfully updated listings.js with ${oct2Articles.length} Oct 2 articles at top and preserved helper functions! Total listings: ${updatedListings.length}`);
}).catch(err => {
  console.error('Error importing listings.js:', err);
  process.exit(1);
});
