import fs from 'fs'
import path from 'path'

const fiveArticles = [
  {
    slug: 'phsa-kp-bs-nursing-admissions-2026',
    title: 'KP Government BS Nursing Admissions 2026–2030 – Apply Online',
    category: 'admissions',
    organization: 'Provincial Health Services Academy (PHSA), Health Dept, Govt of KP',
    jobType: 'Government Nursing Admissions (4-Year Degree)',
    location: 'Khyber Pakhtunkhwa (Peshawar & All Govt Nursing Colleges)',
    qualification: 'FSc Pre-Medical (50% Min Marks) + KMU-CAT + KP/Merged Districts Domicile',
    salary: 'BS Nursing Session 2026–2030 (Govt Stipend as per Rules)',
    lastDate: '2026-10-16',
    publishDate: '2026-10-01',
    officialLink: 'https://www.phsa.edu.pk/admissions',
    featured: true,
    logoInitial: 'PHSA',
    featuredImage: '/images/phsa-kp-bs-nursing-admissions-2026.svg',
    imageAlt: 'KP Government BS Nursing Admissions 2026 PHSA Apply Online',
    excerpt: 'PHSA Khyber Pakhtunkhwa has officially announced online admissions for 4-year BS Nursing (Session 2026-2030) across government nursing colleges. Check FSc Pre-Medical eligibility, KMU-CAT score, domicile rules, and application deadline of October 16, 2026.',
    seoTitle: 'KP Government BS Nursing Admissions 2026–2030 – Apply Online',
    metaDescription: 'Apply online for KP Government BS Nursing Admissions 2026-2030 via PHSA portal (phsa.edu.pk). View eligibility for FSc Pre-Medical, KMU-CAT requirement, nursing colleges, and deadline Oct 16, 2026.',
    isVerified: true,
    schemaType: 'Article',
    content: [
      '### Executive Summary & Official Admission Notice',
      'The **Provincial Health Services Academy (PHSA)**, operating under the Health Department, Government of Khyber Pakhtunkhwa, has officially announced the commencement of online admissions for the **4-Year BS Nursing Degree Program (Session 2026–2030)** across participating government nursing colleges in Khyber Pakhtunkhwa.',
      'Online registration opened on **September 29, 2026**, and candidates seeking admission to government nursing institutions must submit their online applications via the official PHSA Applicant Portal before the closing date of **October 16, 2026**.',
      '### Quick Information Overview Table',
      '- **Degree Program:** Bachelor of Science in Nursing (BS Nursing – 4 Years)',
      '- **Academic Session:** 2026–2030',
      '- **Executing Body:** Provincial Health Services Academy (PHSA), Health Dept, Govt of KP',
      '- **Target Institutions:** Affiliated Government College of Nursing (GCN) Campuses in KP',
      '- **Basic Eligibility:** FSc Pre-Medical (Minimum 50% Marks) & Mandatory KMU-CAT Result',
      '- **Domicile Requirement:** Khyber Pakhtunkhwa (KP) & Merged Districts (FATA)',
      '- **Online Application Opening Date:** September 29, 2026',
      '- **Online Application Deadline:** **October 16, 2026**',
      '- **Official Admission Portal:** [phsa.edu.pk/admissions](https://www.phsa.edu.pk/admissions)',
      '### Academic Eligibility Criteria & Entry Test Requirements',
      'Candidates applying for government nursing admissions in KP must satisfy the following criteria:',
      '- **Educational Qualification:** Higher Secondary School Certificate (HSSC / FSc Pre-Medical) with Physics, Chemistry, and Biology, securing a minimum of **50% unadjusted marks** from a recognized Board of Intermediate and Secondary Education (BISE).',
      '- **KMU-CAT Mandatory Test:** Candidates must have appeared in the **Khyber Medical University Centralized Admission Test (KMU-CAT)**. Entry test marks are integrated into the final merit calculation.',
      '- **Domicile Criteria:** Applicants must possess a valid **Domicile Certificate of Khyber Pakhtunkhwa** or Merged Tribal Districts (FATA).',
      '- **Age Limit:** 18 to 25 years as of the closing date of application (or as specified in the official PHSA prospectus).',
      '### Participating Government Nursing Colleges',
      'Submissions allow applicants to rank participating public sector nursing colleges in KP during online form submission, including:',
      '- College of Nursing, Post Graduate College of Nursing (PGCN), Peshawar',
      '- Government College of Nursing (GCN), Hayatabad, Peshawar',
      '- Government College of Nursing, Mardan',
      '- Government College of Nursing, Swat',
      '- Government College of Nursing, Abbottabad',
      '- Government College of Nursing, Kohat',
      '- Government College of Nursing, Bannu',
      '- Government College of Nursing, D.I. Khan',
      '- Government College of Nursing, Jamrud (Khyber District)',
      '### Step-by-Step "How to Apply Online" Guide',
      '1. **Step 1:** Access the official PHSA Applicant Portal at `https://www.phsa.edu.pk/admissions` (or `phsa.edu.pk/user/register.php`).',
      '2. **Step 2:** Create an applicant account using your CNIC/B-Form number, active mobile number, and personal email address.',
      '3. **Step 3:** Generate and print the auto-generated bank application processing fee challan, deposit the fee at the designated bank, and upload a clear photo/scan of the paid receipt.',
      '4. **Step 4:** Enter your Matric, FSc Pre-Medical, and KMU-CAT test marks exactly as printed on your official DMCs.',
      '5. **Step 5:** Upload clear scanned copies of required documents (CNIC/B-Form, Domicile, FSc DMC, Matric Certificate, Photograph).',
      '6. **Step 6:** Rank your preferred participating nursing colleges in order of preference.',
      '7. **Step 7:** Review your profile carefully and submit before **October 16, 2026**.',
      '### Required Documents Checklist',
      '- Recent Passport-Size Photograph',
      '- CNIC or B-Form copy',
      '- KP / Merged Districts Domicile Certificate',
      '- Matriculation (SSC) Detailed Marks Certificate (DMC)',
      '- FSc Pre-Medical (HSSC) Detailed Marks Certificate (DMC)',
      '- KMU-CAT Official Test Result Card',
      '- Paid Application Fee Bank Voucher / Receipt',
      '- Quota Certificate (if applying under Minority, Disability, or PHSA Network reserved seats)',
      '### Selection & Merit List Procedure',
      '- **Document Verification:** PHSA scrutinizes all online applications and mark entries.',
      '- **Correction Window:** If any discrepancy is identified, the application is returned to the applicant portal with remarks for online correction before final lock.',
      '- **Merit List Display:** Provisional and final merit lists will be published on the PHSA website. Selected candidates must confirm acceptance and submit original documents within 7 working days of merit publication.',
      '- For other health and development opportunities, view the [Punjab CBD Youth Career Program](/jobs/cbd-punjab-paid-internship-2026-youth-career-program).',
      '### Official Source & Apply Links',
      '- **Official Admission Portal:** [PHSA KP Admissions Portal](https://www.phsa.edu.pk/admissions)',
      '- **PHSA Main Website:** [PHSA KP Official Website](https://www.phsa.edu.pk/)',
      '### Frequently Asked Questions (FAQ)',
      '**Q1: What is the last date to apply for PHSA KP BS Nursing Admissions 2026?**\nThe last date to submit online applications on the PHSA portal is **October 16, 2026**.',
      '**Q2: Is KMU-CAT mandatory for KP BS Nursing admission?**\nYes, KMU-CAT entry test marks are mandatory for merit calculation in KP public sector nursing colleges.',
      '**Q3: What is the minimum FSc percentage required?**\nApplicants must have passed FSc Pre-Medical with at least 50% unadjusted marks.',
      '**Q4: Can candidates from other provinces apply on open merit?**\nNo, admissions in KP government nursing colleges are open to candidates holding KP or Merged Districts (FATA) domicile.',
      '**Q5: What is the duration of the BS Nursing degree?**\nBS Nursing is a 4-year undergraduate degree program followed by mandatory internship training.'
    ]
  },
  {
    slug: 'cbd-punjab-paid-internship-2026-youth-career-program',
    title: 'CBD Punjab Paid Internship 2026 – Youth Career Program for Fresh Graduates',
    category: 'internships',
    organization: 'Punjab Central Business District Development Authority (PCBDDA / CBD Punjab)',
    jobType: 'Paid Graduate Internship (Youth Career Program 2026)',
    location: 'Lahore, Punjab',
    qualification: 'Minimum 16 Years Education (BS/BE/BBA/MA/MSc/LLB) • CGPA ≥ 3.0 • Age ≤ 25',
    salary: 'Monthly Paid Internship Stipend + Professional Certificate',
    lastDate: '2026-10-12',
    publishDate: '2026-10-01',
    officialLink: 'https://www.cbdpunjab.gov.pk/ycp2026',
    featured: true,
    logoInitial: 'CBD',
    featuredImage: '/images/cbd-punjab-paid-internship-2026.svg',
    imageAlt: 'CBD Punjab Paid Internship 2026 Youth Career Program Apply Online',
    excerpt: 'CBD Punjab (PCBDDA) has announced the Youth Career Program 2026 offering paid internships up to 3 months for fresh engineering, IT, finance, architecture, HR, and legal graduates. Apply online before October 12, 2026.',
    seoTitle: 'CBD Punjab Paid Internship 2026 – Youth Career Program | Apply Online',
    metaDescription: 'Apply online for CBD Punjab Youth Career Program 2026 (PCBDDA). Paid 3-month internship for fresh graduates (BS/BE, CGPA 3.0, Max Age 25). Deadline: October 12, 2026.',
    isVerified: true,
    schemaType: 'JobPosting',
    content: [
      '### Youth Career Program 2026 (YCP) Overview',
      'The **Punjab Central Business District Development Authority (PCBDDA)**, prominently known as **CBD Punjab**, has officially launched online applications for its flagship **Youth Career Program (YCP) 2026**.',
      'Designed as a high-impact, professional placement scheme, YCP 2026 offers fresh Pakistani university graduates a **paid full-time internship of up to 3 months** across mega infrastructure, corporate finance, urban development, and smart city technology projects.',
      '### Quick Information Summary Table',
      '- **Program Name:** CBD Punjab Youth Career Program 2026 (YCP 2026)',
      '- **Sponsoring Authority:** Punjab Central Business District Development Authority (PCBDDA)',
      '- **Program Nature:** Paid Full-Time Graduate Internship',
      '- **Duration:** Up to 3 Months',
      '- **Stipend Status:** Monthly Paid Internship Stipend (Market Competitive)',
      '- **Work Location:** Lahore, Punjab',
      '- **Target Audience:** Fresh University Graduates (16 Years Education)',
      '- **Application Deadline:** **October 12, 2026**',
      '- **Official Apply Portal:** [cbdpunjab.gov.pk/ycp2026](https://www.cbdpunjab.gov.pk/ycp2026)',
      '### Detailed Academic Eligibility & Requirements',
      'Applicants must meet all official PCBDDA eligibility parameters:',
      '- **Educational Background:** Minimum 16 years of education (BS, BE, BBA, MA, MSc, LLB) from an HEC-recognized university or institution.',
      '- **Academic Merit:** Minimum Cumulative Grade Point Average (**CGPA 3.0 out of 4.0**) or 1st Division equivalent.',
      '- **Age Limit:** Maximum **25 years** as of the application closing date.',
      '- **Experience Level:** Open exclusively to **fresh graduates** seeking initial corporate and engineering exposure.',
      '### Eligible Disciplines & Participating Directorates',
      'Interns will be placed across key operational directorates, including:',
      '- **Technical & Engineering:** Civil Engineering, Electrical Engineering, Mechanical Engineering, Architecture, Urban & Regional Planning, Project Management, Geographic Information System (GIS).',
      '- **Finance & Accounts:** Corporate Finance, Accounting, Financial Planning & Analysis, Internal Audit.',
      '- **Commercial & Marketing:** Business Development, Sales, Corporate Communications, PR & Media Management.',
      '- **IT & Systems:** Software Engineering, Computer Science, IT Support, Database Management.',
      '- **Legal & Procurement:** Law (LLB/LLM), Contracts Management, Supply Chain & Procurement.',
      '- **Land & Operations:** Estate Management, Land Acquisition, Administrative Operations.',
      '### Program Benefits & Professional Certification',
      '- **Monthly Paid Stipend:** Selected candidates receive a monthly financial stipend for the duration of the internship.',
      '- **Hands-On Project Experience:** Direct involvement in real-world commercial and infrastructure developments.',
      '- **Senior Mentorship:** One-on-one guidance from seasoned urban planners, project managers, and corporate leaders.',
      '- **Official Certificate:** Internship Completion Certificate issued by PCBDDA upon successful completion.',
      '### Step-by-Step Online Application Process',
      '1. **Step 1:** Visit the official CBD Punjab YCP portal at `https://www.cbdpunjab.gov.pk/ycp2026` (or `cbdpunjab.gov.pk/career`).',
      '2. **Step 2:** Select **"Youth Career Program 2026"** and register your candidate account.',
      '3. **Step 3:** Enter your personal information, degree title, university name, final CGPA, and year of graduation.',
      '4. **Step 4:** Select your preferred directorate/field of internship.',
      '5. **Step 5:** Upload your updated CV (PDF), academic transcripts, and CNIC copy.',
      '6. **Step 6:** Submit your online application prior to the closing deadline of **October 12, 2026**.',
      'For federal government IT vacancies, also explore [NTISB Cyber Security Jobs 2026](/jobs/ntisb-cyber-security-jobs-2026-national-job-portal).',
      '### Official Apply & Source Links',
      '- **Official YCP 2026 Portal:** [CBD Punjab YCP 2026 Application](https://www.cbdpunjab.gov.pk/ycp2026)',
      '- **CBD Punjab Career Page:** [CBD Punjab Careers](https://www.cbdpunjab.gov.pk/career)',
      '### Frequently Asked Questions (FAQ)',
      '**Q1: What is the last date to apply for CBD Punjab Youth Career Program 2026?**\nThe application deadline is **October 12, 2026**.',
      '**Q2: Is the CBD Punjab internship paid?**\nYes, it is a paid full-time internship offering a monthly stipend.',
      '**Q3: What CGPA is required to apply for YCP 2026?**\nApplicants must have a minimum CGPA of 3.0 out of 4.0 (or equivalent 1st Division).',
      '**Q4: What is the maximum age limit for applicants?**\nThe maximum age limit is 25 years as of the closing date.',
      '**Q5: What is the total duration of the internship?**\nThe internship tenure is up to 3 months.'
    ]
  },
  {
    slug: 'shaikh-ayaz-university-spring-2027-admissions-apply-online',
    title: 'Shaikh Ayaz University Spring 2027 Admissions – Apply Before October 10',
    category: 'admissions',
    organization: 'The Shaikh Ayaz University, Shikarpur (SAUS), Sindh',
    jobType: 'University Spring 2027 Admissions',
    location: 'Shikarpur, Sindh',
    qualification: 'HSC / Intermediate / FSc / ICS / I.Com (50% Min Marks)',
    salary: 'BSCS, BSIT, BS Math & Undergraduate Degree Programs',
    lastDate: '2026-10-10',
    publishDate: '2026-10-01',
    officialLink: 'https://admissions.saus.edu.pk/admissions',
    featured: true,
    logoInitial: 'SAUS',
    featuredImage: '/images/shaikh-ayaz-university-admissions-2027.svg',
    imageAlt: 'Shaikh Ayaz University Spring 2027 Admissions Shikarpur Apply Online',
    excerpt: 'The Shaikh Ayaz University Shikarpur has announced Spring 2027 online admissions for BSCS, BSIT, BS Mathematics, and BBA degree programs. View eligibility, Rs2,500 fee, Entry Test date on Nov 7, and apply before October 10, 2026.',
    seoTitle: 'Shaikh Ayaz University Spring 2027 Admissions – Apply Online',
    metaDescription: 'Shaikh Ayaz University Shikarpur Spring 2027 admissions open for BSCS, BSIT & BS Math. Apply online via saus.edu.pk by Oct 10, 2026. Entry test on Nov 7, 2026.',
    isVerified: true,
    schemaType: 'Article',
    content: [
      '### Academic Overview & Spring 2027 Notice',
      '**The Shaikh Ayaz University, Shikarpur (SAUS)**, a premier public sector university in northern Sindh, has officially invited online applications for **Spring 2027 Admissions** across its undergraduate degree programs.',
      'Prospective students across Sindh and nationwide can submit their online application forms on the university\'s official admissions portal by **October 10, 2026**. The official admission entry test is scheduled for **November 07, 2026**.',
      '### Quick Information Overview Table',
      '- **University Name:** The Shaikh Ayaz University, Shikarpur (SAUS), Sindh',
      '- **Academic Session:** Spring 2027',
      '- **Degree Level:** Undergraduate BS (4-Year) Degree Programs',
      '- **Primary Disciplines:** Computer Science (BSCS), Information Technology (BSIT), Mathematics',
      '- **Application Processing Fee:** Rs. 2,500',
      '- **Online Application Deadline:** **October 10, 2026**',
      '- **Admission Entry Test Date:** **November 07, 2026**',
      '- **Official Apply Portal:** [admissions.saus.edu.pk](https://admissions.saus.edu.pk/admissions)',
      '### Offered Undergraduate Degree Programs',
      '- **BS Computer Science (BSCS):** 4-Year degree program focused on software engineering, algorithms, AI, and systems architecture.',
      '- **BS Information Technology (BSIT):** 4-Year program covering network administration, web technologies, and database management.',
      '- **BS Mathematics:** 4-Year pure and applied mathematical science program.',
      '- **BS Business Administration (BBA) / BS Commerce:** Corporate management and accounting programs.',
      '- **BS English Literature & Linguistics:** Advanced humanities and language studies.',
      '### Eligibility Criteria & Minimum Marks',
      '- **HSC / Intermediate Criteria:** Candidates must have passed Higher Secondary Certificate (HSC-II Pre-Engineering, Pre-Medical, ICS, I.Com, or General Science) with a minimum of **50% marks** from a recognized Intermediate board.',
      '- **Domicile Requirement:** Admissions are open to candidates holding Sindh Domicile and PRC, with reserved seats for self-finance and open merit.',
      '- **Entry Test Mandatory:** Applicants must appear in the SAUS Admission Entry Test on November 07, 2026.',
      '### Merit Calculation & Selection Criteria',
      'Final merit lists are compiled according to the university\'s approved weighted admission formula:',
      '- **Matriculation (SSC):** 10% weightage',
      '- **Intermediate (HSC):** 40% weightage',
      '- **SAUS Entry Test:** 50% weightage',
      '### Step-by-Step Online Application Procedure',
      '1. **Step 1:** Visit the official SAUS Admissions Portal at `https://admissions.saus.edu.pk/admissions` (or `admission.saus.edu.pk`).',
      '2. **Step 2:** Register a new applicant account with your CNIC/B-Form number and mobile number.',
      '3. **Step 3:** Generate the prescribed **Rs. 2,500 Admission Processing Fee** challan voucher.',
      '4. **Step 4:** Pay the processing fee at the designated bank branch and upload a clear scanned image of the paid voucher.',
      '5. **Step 5:** Fill in your academic marks (SSC & HSC) and personal details.',
      '6. **Step 6:** Upload scanned documents (CNIC, Domicile, PRC, SSC & HSC Marksheets, Photo).',
      '7. **Step 7:** Submit your online application form prior to **October 10, 2026**.',
      'For health education admissions in KP, explore our guide on [KP Government BS Nursing Admissions 2026](/jobs/phsa-kp-bs-nursing-admissions-2026).',
      '### Required Documents Checklist',
      '- Recent Passport-size Photograph',
      '- Candidate\'s CNIC / B-Form',
      '- Father\'s / Guardian\'s CNIC',
      '- Sindh Domicile Certificate & PRC (Form D)',
      '- SSC / Matriculation Pass Certificate & Marks Sheet',
      '- HSC / Intermediate Pass Certificate & Marks Sheet',
      '- Paid Rs. 2,500 Bank Processing Fee Receipt',
      '### Official University Contact & Apply Links',
      '- **Official Admission Portal:** [SAUS Online Admission Portal](https://admissions.saus.edu.pk/admissions)',
      '- **Main University Website:** [The Shaikh Ayaz University Official Website](https://saus.edu.pk/)',
      '### Frequently Asked Questions (FAQ)',
      '**Q1: What is the last date to apply for SAUS Spring 2027 Admissions?**\nThe application deadline is **October 10, 2026**.',
      '**Q2: When will the SAUS entry test be conducted?**\nThe admission entry test will be held on **November 07, 2026**.',
      '**Q3: What is the application processing fee?**\nThe admission processing fee is **Rs. 2,500**.',
      '**Q4: What minimum marks are required for BSCS and BSIT?**\nApplicants must have secured at least 50% marks in Intermediate (HSC Pre-Engineering / ICS).',
      '**Q5: Where is Shaikh Ayaz University located?**\nIt is a public sector university located in Shikarpur, Sindh.'
    ]
  },
  {
    slug: 'ntisb-cyber-security-jobs-2026-national-job-portal',
    title: 'Federal Government Cyber Security Jobs 2026 – NTISB Latest Vacancies',
    category: 'government-jobs',
    organization: 'National Telecommunication and Information Security Board (NTISB) / Cabinet Division',
    jobType: 'Federal Government Contract (PPS-5 to PPS-11)',
    location: 'Islamabad, Pakistan',
    qualification: 'BS-CS / BS-IT / Software Eng / Cyber Security / DAE / Graduation',
    salary: 'Pay Scale PPS-5 to PPS-11 Market Competitive Govt Scales',
    lastDate: '2026-10-12',
    publishDate: '2026-10-01',
    officialLink: 'https://njp.gov.pk/jobs/search',
    featured: true,
    logoInitial: 'NTISB',
    featuredImage: '/images/ntisb-cyber-security-jobs-2026.svg',
    imageAlt: 'NTISB Cyber Security Jobs 2026 National Job Portal Apply Online',
    excerpt: 'National Telecommunication and Information Security Board (NTISB) under Cabinet Division is hiring Network Engineers, SOC Analysts (L1/L2/L3), Database Administrators, SIEM Engineers, and Incident Responders via NJP before October 12, 2026.',
    seoTitle: 'Federal Government Cyber Security Jobs 2026 – NTISB Vacancies via NJP',
    metaDescription: 'Apply online for NTISB Cyber Security Jobs 2026 via National Job Portal (njp.gov.pk). Active vacancies for Network Engineer, SOC Analyst, DBA, SIEM Engineer. Deadline: Oct 12, 2026.',
    isVerified: true,
    schemaType: 'JobPosting',
    content: [
      '### Official Recruitment Notice & Overview',
      'The **National Telecommunication and Information Security Board (NTISB)**, operating under the Cabinet Division, Government of Pakistan, has officially advertised high-level technical and cyber security vacancies.',
      'Published on the federal **National Job Portal (NJP)**, these contract appointments (PPS-5 to PPS-11) are aimed at strengthening national cyber defense, FCERT operations, security operations center (SOC) monitoring, and critical telecom infrastructure protection.',
      'Qualified Pakistani candidates must submit their electronic applications online at `njp.gov.pk` before **October 12, 2026**.',
      '### Quick Summary of NTISB Recruitment',
      '- **Organization:** National Telecommunication and Information Security Board (NTISB) / Cabinet Division',
      '- **Job Category:** [Government Jobs](/category/government-jobs) / IT & Cyber Security',
      '- **Scale / Pay:** Project Pay Scales (PPS-5 to PPS-11)',
      '- **Job Location:** Islamabad, Pakistan',
      '- **Application Mode:** Online via National Job Portal (NJP)',
      '- **Closing Date:** **October 12, 2026**',
      '- **Official NJP Portal:** [njp.gov.pk](https://njp.gov.pk/)',
      '### Active Positions & Vacancy Breakdown Table (Verified 2026)',
      'The following table lists active vacancies open for online applications on NJP:',
      '| Position Title | Pay Scale | Minimum Qualification | Min. Experience | Official Deadline |',
      '|---|---|---|---|---|',
      '| Director FCERT | PPS-11 | BS / MS Cyber Security / CS / Telecom | 15+ Years | Oct 12, 2026 |',
      '| Deputy Director (Integration) | PPS-10 | BS / BE Computer Engineering / CS / IT | 12+ Years | Oct 12, 2026 |',
      '| Deputy Director (SOC) | PPS-10 | BS / MS Cyber Security / Computer Science | 10+ Years | Oct 12, 2026 |',
      '| Assistant Director (Integration) | PPS-9 | BS-CS / BS-IT / Software Engineering | 6+ Years | Oct 12, 2026 |',
      '| Database Administrator (DBA) | PPS-8 | BS Computer Science / Software Engineering | 5+ Years | Oct 12, 2026 |',
      '| SOC Analyst L3 / SIEM Engineer | PPS-8 | BS Cyber Security / CS / IT | 5+ Years | Oct 12, 2026 |',
      '| SOC Analyst L2 / Incident Responder | PPS-7 | BS Cyber Security / CS / IT | 4+ Years | Oct 12, 2026 |',
      '| SOC Analyst L1 | PPS-7 | BS Cyber Security / CS / IT | 3+ Years | Oct 12, 2026 |',
      '| Network Engineer | PPS-7 | BS Computer Engineering / Telecom / CS | 3+ Years | Oct 12, 2026 |',
      '| Procurement Officer / Specialist | PPS-7 | Master\'s / BS Supply Chain / Finance / MBA | 3+ Years | Oct 12, 2026 |',
      '| Office Assistant | PPS-5 | Graduation (BA / BSc / BCom) / DAE | 4+ Years | Oct 12, 2026 |',
      '### Detailed Job Responsibilities & Technical Roles',
      '- **Director FCERT & Deputy Director SOC:** Leads National Computer Emergency Response Team (FCERT) operations, national threat intelligence sharing, incident response frameworks, and strategic SOC monitoring.',
      '- **SOC Analysts (L1, L2, L3) & SIEM Engineers:** Monitors enterprise SIEM dashboards, investigates SIEM alerts, conducts triage analysis, coordinates incident response, and authors threat mitigation rules.',
      '- **Database Administrator (DBA):** Manages Oracle/PostgreSQL/SQL Server database architecture, data security, backup recovery plans, and high-availability database clusters.',
      '- **Network Engineer:** Configures enterprise routers, switches, firewalls, VPN tunnels, and network monitoring tools across secure government telecom networks.',
      '### General Eligibility & Age Limit',
      '- **Educational Degrees:** Degrees must be awarded by HEC-recognized universities or accredited boards.',
      '- **General Age Relaxation:** Federal Government 5-year general age relaxation is included in the prescribed upper age limits as per NJP advertisement.',
      '- **Quota & Domicile:** Provincial and regional quotas (Punjab, Sindh Urban/Rural, KP, Balochistan, AJ&K, GB) apply as detailed in individual NJP job listings.',
      '### Step-by-Step Online Application Guide via NJP',
      '1. **Step 1:** Access the official National Job Portal at `https://njp.gov.pk/`.',
      '2. **Step 2:** Search for **"National Telecommunication and Information Security Board"** in the employer search bar.',
      '3. **Step 3:** Select your desired position (e.g., Network Engineer, SOC Analyst, DBA).',
      '4. **Step 4:** Log in to your NJP account or register a new candidate profile.',
      '5. **Step 5:** Complete your online profile by adding educational degrees, work experience, CNIC, and domicile details.',
      '6. **Step 6:** Submit your application electronically before midnight on **October 12, 2026**.',
      'For other federal relief programs, read our article on the [PM Fuel Relief Scheme 2026](/jobs/pm-fuel-relief-scheme-2026-registration-eligibility).',
      '### Official NJP Apply Links',
      '- **Official Application Portal:** [National Job Portal (NJP Live Jobs)](https://njp.gov.pk/jobs/search)',
      '- **Government Gazette:** [NTISB Official Employer Profile on NJP](https://njp.gov.pk/)',
      '### Frequently Asked Questions (FAQ)',
      '**Q1: What is the last date to apply for NTISB Cyber Security Jobs 2026?**\nThe deadline to submit applications on NJP is **October 12, 2026**.',
      '**Q2: How do I apply for NTISB vacancies?**\nAll applications must be submitted online through the National Job Portal at `njp.gov.pk`. Hard copy applications are not accepted.',
      '**Q3: What qualifications are required for SOC Analyst positions?**\nSOC Analyst positions require a BS degree in Cyber Security, Computer Science, IT, or Software Engineering with relevant experience.',
      '**Q4: Is there any application fee for NJP jobs?**\nNo, submitting applications on the National Job Portal (NJP) is free of cost.',
      '**Q5: What are the pay scales for these contract positions?**\nPositions are offered under Project Pay Scales (PPS-5 to PPS-11).'
    ]
  },
  {
    slug: 'commonwealth-scholarships-2027-28-pakistan-hec-csc-uk',
    title: 'Commonwealth Scholarships 2027–28 for Pakistani Students – Master’s & PhD',
    category: 'scholarships',
    organization: 'Higher Education Commission (HEC) & Commonwealth Scholarship Commission (CSC UK)',
    jobType: 'Fully Funded UK Master\'s & PhD Scholarships',
    location: 'United Kingdom Universities (Pakistani & AJ&K Citizens)',
    qualification: '16 Years Education for Master\'s | 17/18 Years for PhD • HEC HAT Score ≥ 60',
    salary: 'Full Tuition + Monthly UK Living Stipend + Return Airfare',
    lastDate: '2026-10-20',
    publishDate: '2026-10-01',
    officialLink: 'https://www.hec.gov.pk/english/HECAnnouncements/Pages/CW-Scholarship.aspx',
    featured: true,
    logoInitial: 'CSC',
    featuredImage: '/images/commonwealth-scholarship-2027-28.svg',
    imageAlt: 'Commonwealth Scholarships 2027 28 HEC CSC UK Apply Online',
    excerpt: 'HEC Pakistan and CSC UK have announced fully funded Commonwealth Scholarships 2027-28 for Master\'s (26 nominations) and PhD (30 nominations) in the UK. Dual application on HEC & CSC portals required before October 20, 2026.',
    seoTitle: 'Commonwealth Scholarships 2027–28 for Pakistani Students – Master’s & PhD',
    metaDescription: 'Apply online for Commonwealth Scholarships 2027-28 for UK Master\'s & PhD via HEC (scholarship.hec.gov.pk) & CSC portals. HAT score ≥ 60 mandatory. Deadline: October 20, 2026.',
    isVerified: true,
    schemaType: 'Article',
    content: [
      '### Executive Summary & Official Announcement',
      'The **Higher Education Commission (HEC)** of Pakistan, in collaboration with the **Commonwealth Scholarship Commission (CSC)** in the United Kingdom, has officially announced the call for applications for the **Commonwealth Scholarships 2027–28**.',
      'Financed by the UK Foreign, Commonwealth & Development Office (FCDO), these prestigious fully funded scholarships enable high-achieving Pakistani and Azad Jammu & Kashmir (AJ&K) scholars to pursue full-time **Master\'s (1-Year)** and **Doctoral (PhD 3-Year)** degree programs at top-ranked universities across the United Kingdom.',
      'Both HEC and CSC online application portals will close on **Tuesday, October 20, 2026** (4:00 PM PST / 16:00 BST).',
      '### Quick Information Overview Table',
      '- **Scholarship Title:** Commonwealth Scholarships 2027/28 (UK)',
      '- **Joint Partners:** Higher Education Commission (HEC Pakistan) & Commonwealth Scholarship Commission (CSC UK)',
      '- **Coverage Level:** Fully Funded (Tuition, Monthly Living Allowance, Airfare, Warm Clothing)',
      '- **Offered Degrees:** 1-Year Master\'s & 3-Year General PhD',
      '- **Mandatory Aptitude Test:** HEC HAT Score **≥ 60 out of 100**',
      '- **Nomination Slots:** **26 Nominations** for Master\'s | **30 Nominations** for General PhD',
      '- **Dual Application Rule:** **MANDATORY** submission on BOTH HEC & CSC portals',
      '- **Closing Deadline:** **October 20, 2026**',
      '- **Official HEC Portal:** [scholarship.hec.gov.pk](https://scholarship.hec.gov.pk/)',
      '### Six Commonwealth Development Themes',
      'Proposed study programs must align directly with one of the six core Commonwealth development themes:',
      '1. **Science and technology for development**',
      '2. **Strengthening health systems and capacity**',
      '3. **Promoting global prosperity**',
      '4. **Strengthening global peace, security and governance**',
      '5. **Strengthening resilience and response to crises**',
      '6. **Access, inclusion and opportunity**',
      '### Detailed Eligibility Criteria for Pakistani & AJ&K Candidates',
      '- **Nationality:** Must be a Pakistani or AJ&K national and permanent resident. Dual nationals are **NOT** eligible.',
      '- **Academic Requirements:**',
      '  - **Master\'s Scholarship:** 16 years of completed education (BS 4-Year, MA, MSc, BE, BBA) with no 3rd division in academic career.',
      '  - **PhD Scholarship:** 17 or 18 years of completed education (MS, MPhil, ME) in a relevant field.',
      '- **Mandatory HEC HAT Score:** Must possess a valid HEC Higher Education Aptitude Test (HAT) score of **minimum 60 out of 100**. (Valid test categories HAT-I, HAT-II, HAT-III, HAT-IV conducted on or after October 25, 2024 are accepted).',
      '- **Age Limit:** No upper age limit.',
      '### MANDATORY Dual Application Requirement',
      '⚠️ **CRITICAL DISQUALIFICATION WARNING:** Candidates **MUST** submit separate online applications on **BOTH** official web portals prior to **October 20, 2026**:',
      '1. **CSC UK Portal:** Submit online application on the official Commonwealth Scholarship Commission portal.',
      '2. **HEC Pakistan Portal:** Submit online application on [scholarship.hec.gov.pk](https://scholarship.hec.gov.pk/).',
      '*Failure to complete application on either portal will result in immediate rejection by HEC.*',
      '### HEC Nomination vs. Final CSC Selection Clarification',
      '**IMPORTANT NOTICE:** Being nominated by HEC does **NOT** guarantee final selection or financial award.',
      'HEC selects and forwards the top 26 Master\'s and 30 PhD candidates to the CSC UK panel. The final selection decisions are made independently by the Commonwealth Scholarship Commission in London based on academic merit, research quality, impact proposal, and UK university placement.',
      '### Step-by-Step Application Guide',
      '1. **Step 1:** Verify that your HEC HAT score is ≥ 60. (If not, register for the next official HAT test intake).',
      '2. **Step 2:** Register on the CSC UK Online Application System and complete your personal profile, development impact statements, and referee details.',
      '3. **Step 3:** Apply directly for admission to up to three participating UK universities.',
      '4. **Step 4:** Log in to the HEC portal at `https://scholarship.hec.gov.pk/`, select **"Learning Opportunities Abroad (LOA) -> Commonwealth Scholarship"**, and fill out the profile.',
      '5. **Step 5:** Upload paid HEC fee deposit voucher (Rs. 1,000) and submit both online applications before **October 20, 2026**.',
      'For teacher exchange opportunities, also view our guide on [Teach in USA BridgeUSA J-1 Program](/jobs/teach-in-usa-bridgeusa-j1-teacher-program-eligibility-guide).',
      '### Official Links & Web Portals',
      '- **HEC Official Announcement:** [HEC Commonwealth Notice](https://www.hec.gov.pk/english/HECAnnouncements/Pages/CW-Scholarship.aspx)',
      '- **HEC Online Portal:** [HEC Scholarship System](https://scholarship.hec.gov.pk/)',
      '### Frequently Asked Questions (FAQ)',
      '**Q1: What is the application deadline for Commonwealth Scholarships 2027–28?**\nBoth HEC and CSC portals close on **October 20, 2026**.',
      '**Q2: What is the minimum HAT score required by HEC?**\nCandidates must have a minimum score of 60/100 in HEC HAT (taken on or after Oct 25, 2024).',
      '**Q3: How many nominations will HEC send to CSC?**\nHEC will send 26 nominations for Master\'s and 30 nominations for General PhD.',
      '**Q4: Is applying on both HEC and CSC portals mandatory?**\nYes. Submitting on only one portal results in automatic disqualification.',
      '**Q5: Does HEC nomination guarantee a UK scholarship?**\nNo. Final selection is conducted by the Commonwealth Scholarship Commission in the UK.'
    ]
  }
]

const filePath = path.resolve(process.cwd(), 'src/data/listings.js')
let fileContent = fs.readFileSync(filePath, 'utf8')

const match = fileContent.match(/export const listings = (\[[\s\S]*?\n\])\s*\n\nexport const getListingBySlug/)

if (match) {
  const existingListingsStr = match[1]
  let existingListings = []
  try {
    existingListings = eval(existingListingsStr)
  } catch (err) {
    console.error('Failed to parse existing listings:', err)
  }

  const newSlugs = new Set(fiveArticles.map(l => l.slug))
  const filteredExisting = existingListings.filter(l => !newSlugs.has(l.slug))

  const combined = [...fiveArticles, ...filteredExisting]

  const newArrayStr = JSON.stringify(combined, null, 2)
  fileContent = fileContent.replace(match[1], newArrayStr)

  fs.writeFileSync(filePath, fileContent, 'utf8')
  console.log(`Successfully updated listings.js with 5 new articles. Total articles: ${combined.length}`)
} else {
  console.error('Could not find listings array in listings.js')
}
