import fs from 'fs'
import path from 'path'

const newListings = [
  {
    slug: 'gwadar-shipyard-cfo-accounts-officer-jobs-2026',
    title: 'Gwadar Shipyard CFO & Accounts Officer Jobs 2026 – Apply Online',
    category: 'government-jobs',
    organization: 'Project Management Cell, Gwadar Shipyard / MoDP',
    jobType: 'Government / Contract (PPS-7)',
    location: 'Gwadar / Islamabad, Pakistan',
    qualification: 'CA / CMA / ACCA / Master\'s degree in Finance or Accounting',
    salary: 'Pay Scale PPS-7 (Market Competitive Govt Contract Pay)',
    lastDate: '2026-09-29',
    publishDate: '2026-09-27',
    officialLink: 'https://njp.gov.pk/jobs/live',
    featured: true,
    logoInitial: 'GS',
    featuredImage: '/images/gwadar-shipyard-cfo-accounts-officer-2026.svg',
    imageAlt: 'Gwadar Shipyard CFO & Accounts Officer Jobs 2026 Banner',
    excerpt: 'Project Management Cell, Gwadar Shipyard under Ministry of Defence Production invites applications for CFO / Accounts Officer (PPS-7). Apply online via National Job Portal by September 29, 2026.',
    seoTitle: 'Gwadar Shipyard CFO & Accounts Officer Jobs 2026 – Apply Online',
    metaDescription: 'Apply online for CFO & Accounts Officer (PPS-7) at Project Management Cell, Gwadar Shipyard (MoDP). Check eligibility criteria, salary scale, and NJP online application deadline of September 29, 2026.',
    content: [
      '### Overview',
      'The Project Management Cell, Gwadar Shipyard, operating under the Ministry of Defence Production (MoDP), Government of Pakistan, has officially announced contract vacancies for the post of Chief Financial Officer (CFO) / Accounts Officer (PPS-7). This key position is responsible for managing financial controls, project accounting, budgeting, and statutory compliance for the shipyard development project.',
      '### Quick Information',
      '- **Organization:** Project Management Cell, Gwadar Shipyard / Ministry of Defence Production (MoDP)',
      '- **Job Scale:** Pay Scale PPS-7 (Contract Basis)',
      '- **Job Category:** [Government Jobs](/category/government-jobs)',
      '- **Location:** Gwadar / Islamabad, Pakistan',
      '- **Qualification:** CA / CMA / ACCA / Master\'s Degree in Finance or Accounting from an HEC-recognized institution',
      '- **Posted Date:** September 27, 2026',
      '- **Application Deadline:** September 29, 2026 ([Closing Soon](/category/closing-soon))',
      '### Available Positions & Vacancy Details',
      '- **Post Title:** CFO / Accounts Officer',
      '- **Pay Scale:** PPS-7',
      '- **Employment Type:** Contract Basis',
      '### Eligibility & Requirements',
      '- **Educational Qualification:** Candidates must possess a professional accounting qualification (CA / CMA / ACCA) or a Master\'s degree (16 years of education) in Finance, Commerce, or Accounting from an HEC-recognized university.',
      '- **Experience:** Relevant professional experience in corporate financial management, government project accounting, auditing, or budget formulation.',
      '- **Skills:** Strong knowledge of Public Sector Financial Rules, taxation, ERP accounting software, and financial reporting standards.',
      '### How to Apply',
      '1. Visit the official National Job Portal (NJP) at `https://njp.gov.pk/jobs/live`.',
      '2. Locate the vacancy for CFO / Accounts Officer under Project Management Cell, Gwadar Shipyard (MoDP).',
      '3. Register or log in to your NJP account and fill in your educational and professional profile.',
      '4. Submit your electronic application before the closing date of September 29, 2026.',
      '### Important Dates',
      '- **Announcement Date:** September 2026',
      '- **Online Application Deadline:** September 29, 2026',
      '### Official Source & Application Links',
      '- **Official Portal:** [National Job Portal (NJP)](https://njp.gov.pk/jobs/live)',
      '- **Apply Online:** [Submit Application on NJP](https://njp.gov.pk/jobs/live)',
      'CareerDost is an independent information platform. Applicants should verify all details from the official source before applying.'
    ]
  },
  {
    slug: 'gwadar-shipyard-assistant-jobs-2026',
    title: 'Gwadar Shipyard Assistant Jobs 2026 – Apply Online via NJP',
    category: 'government-jobs',
    organization: 'Project Management Cell, Gwadar Shipyard / MoDP',
    jobType: 'Government / Contract (PPS-5)',
    location: 'Gwadar / Islamabad, Pakistan',
    qualification: 'Bachelor\'s Degree (14-16 Years) from an HEC-recognized university',
    salary: 'Pay Scale PPS-5',
    lastDate: '2026-09-29',
    publishDate: '2026-09-27',
    officialLink: 'https://njp.gov.pk/jobs/live',
    featured: true,
    logoInitial: 'GS',
    featuredImage: '/images/gwadar-shipyard-assistant-pps5-2026.svg',
    imageAlt: 'Gwadar Shipyard Assistant PPS-5 Jobs 2026 Banner',
    excerpt: 'Apply online for Assistant (PPS-5) position at Project Management Cell, Gwadar Shipyard under Ministry of Defence Production. Deadline is September 29, 2026 on National Job Portal.',
    seoTitle: 'Gwadar Shipyard Assistant Jobs 2026 – Apply Online via NJP',
    metaDescription: 'Project Management Cell Gwadar Shipyard (MoDP) invites online applications for Assistant (PPS-5). Check eligibility, application process, and deadline of September 29, 2026 on NJP.',
    content: [
      '### Overview',
      'Project Management Cell, Gwadar Shipyard under the Ministry of Defence Production (MoDP) is hiring qualified individuals for the position of Assistant (PPS-5) on a contract basis. The selected candidate will provide administrative, secretarial, and operational support to project managers in daily administrative tasks.',
      '### Quick Information',
      '- **Organization:** Project Management Cell, Gwadar Shipyard / MoDP',
      '- **Job Scale:** Pay Scale PPS-5 (Contract Basis)',
      '- **Job Category:** [Government Jobs](/category/government-jobs)',
      '- **Location:** Gwadar / Islamabad, Pakistan',
      '- **Qualification:** Bachelor\'s Degree (BA / BSc / BCom / BS) from an HEC-recognized university',
      '- **Posted Date:** September 27, 2026',
      '- **Application Deadline:** September 29, 2026 ([Closing Soon](/category/closing-soon))',
      '### Available Positions & Vacancy Details',
      '- **Position:** Assistant',
      '- **Pay Scale:** PPS-5',
      '- **Nature of Post:** Government Contract',
      '### Eligibility Criteria & Requirements',
      '- **Qualification:** Minimum Bachelor\'s Degree (14 or 16 years of education) from an HEC-recognized university.',
      '- **Computer Skills:** Proficiency in MS Office (Word, Excel, PowerPoint) and official correspondence drafting.',
      '- **Age Limit & Quota:** As per Federal Government rules for PPS project appointments.',
      '### How to Apply',
      '1. Access the National Job Portal (NJP) at `https://njp.gov.pk/jobs/live`.',
      '2. Search for Assistant (PPS-5) under Gwadar Shipyard MoDP.',
      '3. Complete your NJP profile and upload educational documents.',
      '4. Submit your online application prior to September 29, 2026.',
      '### Important Dates',
      '- **Posted Date:** September 27, 2026',
      '- **Last Date to Apply:** September 29, 2026',
      '### Official Source',
      '- **Official Source & Apply Portal:** [National Job Portal Live Jobs](https://njp.gov.pk/jobs/live)',
      'CareerDost is an independent information platform. Applicants should verify all details from the official source before applying.'
    ]
  },
  {
    slug: 'imarat-finance-intern-jobs-2026',
    title: 'IMARAT Finance Intern Jobs 2026 – Apply Online',
    category: 'internships',
    organization: 'IMARAT Group of Companies',
    jobType: 'Private / Paid Internship',
    location: 'Islamabad / Rawalpindi, Pakistan',
    qualification: 'Fresh Graduates / Final Year Students in BBA, BS Finance, BS Accounting & Finance, or ACCA',
    salary: 'Stipend Provided',
    lastDate: '2026-09-30',
    publishDate: '2026-09-27',
    officialLink: 'https://careers.imarat.com.pk/Job/JobDetailIndex?JobID=2547',
    featured: true,
    logoInitial: 'IM',
    featuredImage: '/images/imarat-finance-intern-2026.svg',
    imageAlt: 'IMARAT Group Finance Internship 2026 Official Banner',
    excerpt: 'IMARAT Group of Companies is offering a Finance Internship for fresh graduates and undergraduate students in Finance/Accounting. Apply online before September 30, 2026.',
    seoTitle: 'IMARAT Finance Intern Jobs 2026 – Apply Online',
    metaDescription: 'Apply online for Finance Internship 2026 at IMARAT Group. Open to fresh graduates and students in BBA, BS Finance, and ACCA. Application closing date is September 30, 2026.',
    content: [
      '### Overview',
      'IMARAT Group of Companies, one of Pakistan\'s leading real estate development and corporate groups, is accepting applications for its Finance Internship Program 2026. This opportunity is designed for ambitious fresh graduates and undergraduate students looking to build practical expertise in corporate financial analysis, treasury, bookkeeping, and financial reporting.',
      '### Quick Information',
      '- **Organization:** IMARAT Group of Companies',
      '- **Job Type:** Internship (Paid)',
      '- **Job Category:** [Internships](/category/internships) / [Private Jobs](/category/private-jobs)',
      '- **Location:** Islamabad / Rawalpindi, Pakistan',
      '- **Qualification:** Fresh Graduates or Students in BBA, BS Finance, Accounting & Finance, or ACCA',
      '- **Posted Date:** September 27, 2026',
      '- **Last Date to Apply:** September 30, 2026 ([Closing Soon](/category/closing-soon))',
      '### Available Positions & Vacancy Details',
      '- **Position Title:** Finance Intern',
      '- **Department:** Finance & Accounts',
      '- **Duration:** 2 to 3 Months (with potential performance-based job placement)',
      '### Eligibility & Requirements',
      '- **Education:** Fresh graduates or currently enrolled students in Bachelor\'s (BBA / BS Finance / BS Accounting) or professional accounting streams (ACCA / CMA foundation).',
      '- **Key Competencies:** Basic understanding of accounting principles, financial statements, Excel spreadsheets, and analytical problem-solving.',
      '### How to Apply',
      '1. Visit the IMARAT Careers Job Detail page at `https://careers.imarat.com.pk/Job/JobDetailIndex?JobID=2547`.',
      '2. Click on \'Apply for this Job\'.',
      '3. Upload your updated resume/CV and fill in basic details.',
      '4. Submit your application before September 30, 2026.',
      '### Important Dates',
      '- **Announcement Date:** September 2026',
      '- **Closing Date:** September 30, 2026',
      '### Official Source',
      '- **Official Career Portal:** [IMARAT Careers Job Detail](https://careers.imarat.com.pk/Job/JobDetailIndex?JobID=2547)',
      'CareerDost is an independent information platform. Applicants should verify all details from the official source before applying.'
    ]
  },
  {
    slug: 'karachi-shipyard-technical-assistant-jobs-2026',
    title: 'Karachi Shipyard Technical Assistant Jobs 2026 – Apply Online',
    category: 'government-jobs',
    organization: 'Karachi Shipyard & Engineering Works (KSEW)',
    jobType: 'Full Time / Contract',
    location: 'Karachi, Sindh',
    qualification: 'DAE (Mechanical / Naval Architecture / Shipbuilding) from a recognized Board',
    salary: 'Market Competitive Salary Package with KSEW Benefits',
    lastDate: '2026-10-05',
    publishDate: '2026-09-27',
    officialLink: 'https://karachishipyard.com.pk/page/careers',
    featured: true,
    logoInitial: 'KS',
    featuredImage: '/images/karachi-shipyard-technical-assistant-2026.svg',
    imageAlt: 'Karachi Shipyard Technical Assistant Jobs 2026 Banner',
    excerpt: 'Karachi Shipyard & Engineering Works (KSEW) invites applications for Technical Assistant in the Ship Building Department. Closing date is October 5, 2026.',
    seoTitle: 'Karachi Shipyard Technical Assistant Jobs 2026 – Apply Online',
    metaDescription: 'Karachi Shipyard & Engineering Works (KSEW) announced 1 Technical Assistant vacancy in Ship Building Dept. Check DAE eligibility, requirements, and apply before October 5, 2026.',
    content: [
      '### Overview',
      'Karachi Shipyard & Engineering Works (KSEW), a premier naval shipbuilding and industrial engineering enterprise under the Ministry of Defence Production, has announced 1 vacancy for the post of Technical Assistant in its Ship Building Department.',
      '### Quick Information',
      '- **Organization:** Karachi Shipyard & Engineering Works (KSEW)',
      '- **Department:** Ship Building',
      '- **Job Category:** [Government Jobs](/category/government-jobs)',
      '- **Location:** Karachi, Sindh',
      '- **Qualification:** DAE (Mechanical / Naval Architecture / Shipbuilding) from a recognized Board of Technical Education',
      '- **Total Openings:** 1 Position',
      '- **Posted Date:** September 27, 2026',
      '- **Last Date to Apply:** October 05, 2026',
      '### Available Positions & Vacancy Details',
      '- **Position:** Technical Assistant',
      '- **Openings:** 1 Post',
      '- **Department:** Ship Building Division',
      '### Eligibility & Requirements',
      '- **Education:** 3-Year Diploma of Associate Engineer (DAE) in Mechanical, Naval Architecture, or relevant technical field.',
      '- **Experience:** Technical knowledge of shipbuilding processes, structural fabrication drawings, quality assurance, or workshop machinery operation.',
      '- **Age & Physical Fitness:** As per KSEW recruitment regulations.',
      '### How to Apply',
      '1. Visit the Karachi Shipyard careers page at `https://karachishipyard.com.pk/page/careers`.',
      '2. Download the official job application form or follow online instructions.',
      '3. Submit your application along with attested copies of DAE marksheets, CNIC, domicile, and experience certificates.',
      '4. Ensure your application reaches KSEW before October 5, 2026.',
      '### Important Dates',
      '- **Published Date:** September 27, 2026',
      '- **Application Deadline:** October 05, 2026',
      '### Official Source',
      '- **Official Website:** [KSEW Careers Page](https://karachishipyard.com.pk/page/careers)',
      'CareerDost is an independent information platform. Applicants should verify all details from the official source before applying.'
    ]
  },
  {
    slug: 'bank-of-punjab-relationship-officer-transaction-banking-2026',
    title: 'Bank of Punjab Relationship Officer Jobs 2026 – Transaction Banking Karachi',
    category: 'bank-jobs',
    organization: 'The Bank of Punjab (BOP)',
    jobType: 'Bank / Full Time',
    location: 'Karachi, Sindh',
    qualification: 'Bachelor\'s / Master\'s degree in Business Administration, Banking, Finance, or Commerce',
    salary: 'Market Competitive Banking Package',
    lastDate: '2026-10-06',
    publishDate: '2026-09-27',
    officialLink: 'https://www.bop.com.pk/Available-Jobs',
    featured: true,
    logoInitial: 'BOP',
    featuredImage: '/images/bop-relationship-officer-transaction-banking-2026.svg',
    imageAlt: 'Bank of Punjab Relationship Officer Jobs 2026 Karachi Banner',
    excerpt: 'The Bank of Punjab (BOP) is hiring a Relationship Officer – Transaction Banking Sales (South) in Karachi. Apply online via BOP Careers portal by October 6, 2026.',
    seoTitle: 'Bank of Punjab Relationship Officer Jobs 2026 – Transaction Banking Karachi',
    metaDescription: 'Apply online for Relationship Officer (Transaction Banking Sales) at Bank of Punjab in Karachi. Check eligibility criteria, qualifications, and deadline of October 6, 2026.',
    content: [
      '### Overview',
      'The Bank of Punjab (BOP), one of Pakistan\'s fastest-growing commercial banks, is seeking an experienced or high-potential candidate for the role of Relationship Officer – Transaction Banking Sales (South) located in Karachi. The role focuses on cash management, trade services, client acquisition, and corporate relationship building.',
      '### Quick Information',
      '- **Organization:** The Bank of Punjab (BOP)',
      '- **Department:** Transaction Banking Sales (South)',
      '- **Job Category:** [Bank Jobs](/category/bank-jobs)',
      '- **Location:** Karachi, Sindh',
      '- **Qualification:** Bachelor\'s or Master\'s degree in Business Administration, Banking, Finance, or related field',
      '- **Posted Date:** September 27, 2026',
      '- **Application Deadline:** October 06, 2026',
      '### Available Positions & Vacancy Details',
      '- **Position:** Relationship Officer – Transaction Banking Sales (South)',
      '- **Employment Type:** Regular / Full-Time Banking Staff',
      '### Eligibility & Requirements',
      '- **Educational Background:** Bachelor\'s (16 years) or Master\'s degree in Business Administration (MBA / BBA), Banking & Finance, or Economics from an HEC recognized institution.',
      '- **Skills:** Sales drive, understanding of commercial banking transaction products (cash management, payments, collections), client relationship management, and communication skills.',
      '### How to Apply',
      '1. Visit the BOP Available Jobs portal at `https://www.bop.com.pk/Available-Jobs`.',
      '2. Search for \'Relationship Officer – Transaction Banking Sales (South)\'.',
      '3. Click \'Apply Now\' and fill out your online resume profile.',
      '4. Submit your application prior to October 6, 2026.',
      '### Important Dates',
      '- **Announcement Date:** September 2026',
      '- **Closing Date:** October 06, 2026',
      '### Official Source',
      '- **Official Careers Portal:** [Bank of Punjab Available Jobs](https://www.bop.com.pk/Available-Jobs)',
      'CareerDost is an independent information platform. Applicants should verify all details from the official source before applying.'
    ]
  },
  {
    slug: 'bank-of-punjab-relationship-manager-officer-cfc-jobs-2026',
    title: 'Bank of Punjab Relationship Manager & Officer Jobs 2026 – Apply Online',
    category: 'bank-jobs',
    organization: 'The Bank of Punjab (BOP)',
    jobType: 'Bank / Full Time',
    location: 'Lahore, Gujranwala, Faisalabad, Multan, Karachi',
    qualification: 'Graduation / Post Graduation in Business Administration, Finance, or Commerce',
    salary: 'Market Competitive Banking Salary Package',
    lastDate: '2026-10-08',
    publishDate: '2026-09-27',
    officialLink: 'https://www.bop.com.pk/Available-Jobs',
    featured: true,
    logoInitial: 'BOP',
    featuredImage: '/images/bop-relationship-manager-officer-cfc-2026.svg',
    imageAlt: 'Bank of Punjab Relationship Manager & Officer CFC Jobs 2026 Banner',
    excerpt: 'The Bank of Punjab (BOP) is recruiting Relationship Managers and Relationship Officers (CFC) across Lahore, Gujranwala, Faisalabad, Multan, and Karachi. Apply before October 8, 2026.',
    seoTitle: 'Bank of Punjab Relationship Manager & Officer Jobs 2026 – Apply Online',
    metaDescription: 'Apply online for Relationship Manager / Officer CFC positions at Bank of Punjab across major cities. Check eligibility, location options, and deadline of October 8, 2026.',
    content: [
      '### Overview',
      'The Bank of Punjab (BOP) has opened applications for Relationship Manager and Relationship Officer positions within its Corporate & Finance Centers (CFC). Postings are available in major commercial hubs including Lahore, Gujranwala, Faisalabad, Multan, and Karachi.',
      '### Quick Information',
      '- **Organization:** The Bank of Punjab (BOP)',
      '- **Department:** Corporate & Finance Center (CFC)',
      '- **Job Category:** [Bank Jobs](/category/bank-jobs)',
      '- **Locations:** Lahore, Gujranwala, Faisalabad, Multan, Karachi',
      '- **Qualification:** Graduation / Post Graduation in Business Administration, Finance, or Commerce',
      '- **Posted Date:** September 27, 2026',
      '- **Application Deadline:** October 08, 2026',
      '### Available Positions & Vacancy Details',
      '- **Position Titles:** Relationship Manager CFC / Relationship Officer CFC',
      '- **Work Locations:** Lahore, Gujranwala, Faisalabad, Multan, Karachi',
      '### Eligibility & Requirements',
      '- **Educational Qualification:** Bachelor\'s (16 Years) or Master\'s degree in Business, Finance, Economics, or relevant disciplines from HEC recognized universities.',
      '- **Experience:** Prior experience in commercial or corporate lending, portfolio management, credit analysis, or business development in commercial banks.',
      '### How to Apply',
      '1. Visit the BOP official careers portal at `https://www.bop.com.pk/Available-Jobs`.',
      '2. Select the Relationship Manager / Officer CFC position matching your city preference.',
      '3. Fill out the application form and upload your detailed CV.',
      '4. Submit your application online before October 8, 2026.',
      '### Important Dates',
      '- **Posted Date:** September 27, 2026',
      '- **Application Deadline:** October 08, 2026',
      '### Official Source',
      '- **Official Job Portal:** [BOP Careers Page](https://www.bop.com.pk/Available-Jobs)',
      'CareerDost is an independent information platform. Applicants should verify all details from the official source before applying.'
    ]
  },
  {
    slug: 'askari-bank-sr-officer-artificial-intelligence-jobs-2026',
    title: 'Askari Bank AI Jobs 2026 – Sr. Officer Artificial Intelligence',
    category: 'bank-jobs',
    organization: 'Askari Bank Limited',
    jobType: 'Bank / Full Time',
    location: 'Islamabad, Pakistan',
    qualification: 'Bachelor\'s or Master\'s degree in Computer Science, Artificial Intelligence, Data Science, or Software Engineering',
    salary: 'Market Competitive Banking Pay Package',
    lastDate: '2026-10-10',
    publishDate: '2026-09-25',
    officialLink: 'https://careers.askaribank.com.pk/psc/onboard/EMPLOYEE/HRMS/c/HRS_HRAM_FL.HRS_CG_SEARCH_FL.GBL?Action=U&PAGE=HRS_APP_SCHJOB_FL&Page=HRS_APP_SCHJOB_FL&page=HRS_APP_SCHJOB_FL',
    featured: true,
    logoInitial: 'AKBL',
    featuredImage: '/images/askari-bank-sr-officer-ai-2026.svg',
    imageAlt: 'Askari Bank Sr Officer Artificial Intelligence Jobs 2026 Banner',
    excerpt: 'Askari Bank is hiring a Senior Officer Artificial Intelligence (Job ID: 18053) in the Digital Technology & Agile department at Islamabad. Apply online before October 10, 2026.',
    seoTitle: 'Askari Bank AI Jobs 2026 – Sr. Officer Artificial Intelligence',
    metaDescription: 'Apply online for Sr. Officer Artificial Intelligence (Job ID 18053) at Askari Bank Islamabad. Check CS/AI degree eligibility, technology role details, and deadline of October 10, 2026.',
    content: [
      '### Overview',
      'Askari Bank Limited is inviting applications for the position of Senior Officer Artificial Intelligence (Job ID: 18053) within its Digital Technology & Agile Division at the Head Office in Islamabad. This role focuses on driving AI initiatives, machine learning models, predictive analytics, and automated decision engines across banking workflows.',
      '### Quick Information',
      '- **Organization:** Askari Bank Limited',
      '- **Job ID:** 18053',
      '- **Department:** Digital Technology & Agile',
      '- **Job Category:** [Bank Jobs](/category/bank-jobs) / [IT Jobs](/category/it-jobs)',
      '- **Location:** Islamabad, Pakistan',
      '- **Qualification:** Bachelor\'s or Master\'s in Computer Science, AI, Data Science, or Software Engineering',
      '- **Posted Date:** September 25, 2026',
      '- **Application Deadline:** October 10, 2026',
      '### Available Positions & Vacancy Details',
      '- **Position Title:** Sr. Officer Artificial Intelligence',
      '- **Division:** Digital Technology & Agile',
      '### Eligibility & Requirements',
      '- **Educational Qualification:** BS / MS in Computer Science, Artificial Intelligence, Data Science, Software Engineering, or related technical field from an HEC recognized university.',
      '- **Technical Expertise:** Experience in Python, TensorFlow, PyTorch, SQL, Machine Learning pipelines, NLP, or LLM integrations.',
      '- **Experience:** Relevant experience in software development, data science, or AI project execution.',
      '### How to Apply',
      '1. Access the Askari Bank Careers Portal at `https://careers.askaribank.com.pk`.',
      '2. Search for Job ID 18053 (Sr. Officer Artificial Intelligence).',
      '3. Create your applicant profile and upload your resume.',
      '4. Submit your online application prior to October 10, 2026.',
      '### Important Dates',
      '- **Date Posted:** September 25, 2026',
      '- **Closing Date:** October 10, 2026',
      '### Official Source',
      '- **Official Job Portal:** [Askari Bank Careers Portal](https://careers.askaribank.com.pk)',
      'CareerDost is an independent information platform. Applicants should verify all details from the official source before applying.'
    ]
  },
  {
    slug: 'navttc-assistant-private-secretary-jobs-2026',
    title: 'NAVTTC Assistant Private Secretary Jobs 2026 – Apply Online',
    category: 'government-jobs',
    organization: 'National Vocational & Technical Training Commission (NAVTTC)',
    jobType: 'Government (BPS-16)',
    location: 'Islamabad / All Pakistan Quota',
    qualification: 'Graduation (14-16 Years) + Shorthand (100 wpm) & Typing (40 wpm)',
    salary: 'BPS-16 Federal Government Pay Scale',
    lastDate: '2026-10-10',
    publishDate: '2026-09-27',
    officialLink: 'https://jobs.gov.pk/?cat_id=28',
    featured: true,
    logoInitial: 'NAV',
    featuredImage: '/images/navttc-assistant-private-secretary-2026.svg',
    imageAlt: 'NAVTTC Assistant Private Secretary BPS-16 Jobs 2026 Banner',
    excerpt: 'National Vocational and Technical Training Commission (NAVTTC) announces 11 vacancies for Assistant Private Secretary (BPS-16). Apply online via jobs.gov.pk by October 10, 2026.',
    seoTitle: 'NAVTTC Assistant Private Secretary Jobs 2026 – Apply Online',
    metaDescription: 'Apply online for 11 Assistant Private Secretary (BPS-16) posts at NAVTTC via jobs.gov.pk. Check eligibility criteria, shorthand/typing requirements, and deadline of October 10, 2026.',
    content: [
      '### Overview',
      'The National Vocational and Technical Training Commission (NAVTTC), under the Ministry of Federal Education and Professional Training, has invited online applications from qualified Pakistani citizens for 11 posts of Assistant Private Secretary (BPS-16) on a regular/contract basis.',
      '### Quick Information',
      '- **Organization:** National Vocational & Technical Training Commission (NAVTTC)',
      '- **Pay Scale:** BPS-16',
      '- **Total Vacancies:** 11 Posts',
      '- **Job Category:** [Government Jobs](/category/government-jobs)',
      '- **Location:** Islamabad / All Pakistan Quota',
      '- **Qualification:** Graduation (14-16 Years) + Shorthand (100 wpm) & Typing (40 wpm)',
      '- **Posted Date:** September 27, 2026',
      '- **Application Deadline:** October 10, 2026',
      '### Available Positions & Vacancy Details',
      '- **Position Name:** Assistant Private Secretary',
      '- **BPS Grade:** BPS-16',
      '- **Number of Vacancies:** 11 Positions',
      '### Eligibility Criteria & Requirements',
      '- **Educational Qualification:** Graduation (BA / BSc / BCom / BS) from an HEC-recognized university.',
      '- **Technical Skills:** Minimum shorthand speed of 100 words per minute (wpm) and typing speed of 40 words per minute.',
      '- **Computer Knowledge:** Must be proficient in computer applications (MS Word, Excel, InPage).',
      '### How to Apply',
      '1. Go to the official National Employment Exchange Tool / National Job Portal at `https://jobs.gov.pk/?cat_id=28`.',
      '2. Locate the NAVTTC Assistant Private Secretary (BPS-16) job listing.',
      '3. Fill in your personal details, academic qualifications, and shorthand test details.',
      '4. Submit your online application form before October 10, 2026.',
      '### Important Dates',
      '- **Posted Date:** September 27, 2026',
      '- **Last Date to Apply:** October 10, 2026',
      '### Official Source',
      '- **Official Portal:** [National Job Portal NAVTTC Vacancies](https://jobs.gov.pk/?cat_id=28)',
      'CareerDost is an independent information platform. Applicants should verify all details from the official source before applying.'
    ]
  },
  {
    slug: 'navttc-assistant-bps15-jobs-2026',
    title: 'NAVTTC Assistant Jobs 2026 – Apply Online (15 Vacancies)',
    category: 'government-jobs',
    organization: 'National Vocational & Technical Training Commission (NAVTTC)',
    jobType: 'Government (BPS-15)',
    location: 'Islamabad / All Pakistan Quota',
    qualification: 'Graduation (Bachelor\'s Degree in any discipline)',
    salary: 'BPS-15 Federal Government Pay Scale',
    lastDate: '2026-10-10',
    publishDate: '2026-09-27',
    officialLink: 'https://jobs.gov.pk/?cat_id=28',
    featured: true,
    logoInitial: 'NAV',
    featuredImage: '/images/navttc-assistant-bps15-2026.svg',
    imageAlt: 'NAVTTC Assistant BPS-15 Jobs 2026 Official Banner',
    excerpt: 'NAVTTC has opened applications for 15 posts of Assistant (BPS-15). Candidates across Pakistan can apply online at jobs.gov.pk before October 10, 2026.',
    seoTitle: 'NAVTTC Assistant Jobs 2026 – Apply Online (15 Vacancies)',
    metaDescription: 'Apply online for 15 Assistant (BPS-15) vacancies at NAVTTC. Check graduation eligibility criteria, provincial quota breakdown, and application deadline of October 10, 2026.',
    content: [
      '### Overview',
      'National Vocational and Technical Training Commission (NAVTTC) is hiring 15 Assistants (BPS-15) to manage administrative, record-keeping, and office correspondence duties at its headquarters and regional offices across Pakistan.',
      '### Quick Information',
      '- **Organization:** National Vocational & Technical Training Commission (NAVTTC)',
      '- **Pay Scale:** BPS-15',
      '- **Total Vacancies:** 15 Posts',
      '- **Job Category:** [Government Jobs](/category/government-jobs)',
      '- **Location:** Islamabad / All Pakistan Quota',
      '- **Qualification:** Graduation (Bachelor\'s Degree) from an HEC-recognized university',
      '- **Posted Date:** September 27, 2026',
      '- **Application Deadline:** October 10, 2026',
      '### Available Positions & Vacancy Details',
      '- **Position Name:** Assistant',
      '- **Pay Scale:** BPS-15',
      '- **Number of Vacancies:** 15 Posts',
      '### Eligibility & Requirements',
      '- **Educational Qualification:** Graduate (14 or 16 years of education in any discipline) from an HEC-recognized university.',
      '- **IT Training:** Mandatory 6-week Basic IT Training Course (including MS Office) from NITB prior to completion of probation.',
      '### How to Apply',
      '1. Visit the National Job Portal at `https://jobs.gov.pk/?cat_id=28`.',
      '2. Select Assistant (BPS-15) under NAVTTC openings.',
      '3. Log in with your CNIC and complete the online form.',
      '4. Submit your application prior to the closing date of October 10, 2026.',
      '### Important Dates',
      '- **Announcement Date:** September 2026',
      '- **Application Deadline:** October 10, 2026',
      '### Official Source',
      '- **Official Job Portal:** [National Job Portal NAVTTC Jobs](https://jobs.gov.pk/?cat_id=28)',
      'CareerDost is an independent information platform. Applicants should verify all details from the official source before applying.'
    ]
  },
  {
    slug: 'navttc-director-bps18-jobs-2026',
    title: 'NAVTTC Director Jobs 2026 – Apply Online (10 Vacancies)',
    category: 'government-jobs',
    organization: 'National Vocational & Technical Training Commission (NAVTTC)',
    jobType: 'Government (BPS-18)',
    location: 'Islamabad / Regional Headquarters',
    qualification: 'Master\'s Degree (16-18 Years Education) in Public Administration, Management, Engineering, or Social Sciences',
    salary: 'BPS-18 Federal Government Pay Scale & Executive Allowances',
    lastDate: '2026-10-10',
    publishDate: '2026-09-27',
    officialLink: 'https://jobs.gov.pk/?cat_id=28',
    featured: true,
    logoInitial: 'NAV',
    featuredImage: '/images/navttc-director-bps18-2026.svg',
    imageAlt: 'NAVTTC Director BPS-18 Jobs 2026 Banner',
    excerpt: 'National Vocational & Technical Training Commission (NAVTTC) invites applications for 10 vacancies of Director (BPS-18). Apply online through jobs.gov.pk by October 10, 2026.',
    seoTitle: 'NAVTTC Director Jobs 2026 – Apply Online (10 Vacancies)',
    metaDescription: 'NAVTTC announced 10 Director (BPS-18) positions. Check Master\'s degree eligibility, experience requirements, and online application closing date of October 10, 2026 on jobs.gov.pk.',
    content: [
      '### Overview',
      'National Vocational and Technical Training Commission (NAVTTC) invites applications for 10 positions of Director (BPS-18). Directors will lead technical education policy, skill development initiatives, international accreditation programs, and regional operations.',
      '### Quick Information',
      '- **Organization:** National Vocational & Technical Training Commission (NAVTTC)',
      '- **Pay Scale:** BPS-18',
      '- **Total Vacancies:** 10 Positions',
      '- **Job Category:** [Government Jobs](/category/government-jobs)',
      '- **Location:** Islamabad / Regional Headquarters',
      '- **Qualification:** Master\'s Degree (16-18 Years Education) from an HEC-recognized university',
      '- **Posted Date:** September 27, 2026',
      '- **Application Deadline:** October 10, 2026',
      '### Available Positions & Vacancy Details',
      '- **Position Title:** Director',
      '- **BPS Scale:** BPS-18',
      '- **Total Posts:** 10 Vacancies',
      '### Eligibility & Requirements',
      '- **Educational Qualification:** Master\'s degree (16 or 18 years of education) in Public Administration, Business Administration, Engineering, Education, or Social Sciences from an HEC recognized institution.',
      '- **Experience:** Professional experience in administrative management, vocational education planning, or project administration.',
      '### How to Apply',
      '1. Visit the official jobs portal at `https://jobs.gov.pk/?cat_id=28`.',
      '2. Locate the vacancy for Director (BPS-18) under NAVTTC.',
      '3. Fill out the application form with your academic degrees and professional experience.',
      '4. Submit your online application before October 10, 2026.',
      '### Important Dates',
      '- **Posted Date:** September 27, 2026',
      '- **Closing Date:** October 10, 2026',
      '### Official Source',
      '- **Official Source & Apply Portal:** [National Job Portal NAVTTC Category](https://jobs.gov.pk/?cat_id=28)',
      'CareerDost is an independent information platform. Applicants should verify all details from the official source before applying.'
    ]
  }
]

const filePath = path.resolve(process.cwd(), 'src/data/listings.js')
let fileContent = fs.readFileSync(filePath, 'utf8')

// We will read existing listings array out of the file, prepend newListings, and write it back
const match = fileContent.match(/export const listings = (\[[\s\S]*?\n\])\s*\n\nexport const getListingBySlug/)

if (match) {
  const existingListingsStr = match[1]
  let existingListings = []
  try {
    existingListings = eval(existingListingsStr)
  } catch (err) {
    console.error('Failed to parse existing listings:', err)
  }

  // Filter out any duplicates if they exist
  const newSlugs = new Set(newListings.map(l => l.slug))
  const filteredExisting = existingListings.filter(l => !newSlugs.has(l.slug))

  const combined = [...newListings, ...filteredExisting]

  const newArrayStr = JSON.stringify(combined, null, 2)
  fileContent = fileContent.replace(match[1], newArrayStr)

  fs.writeFileSync(filePath, fileContent, 'utf8')
  console.log(`Successfully updated listings.js with ${newListings.length} new jobs. Total: ${combined.length}`)
} else {
  console.error('Could not find listings array in listings.js')
}
